package danger

// Code generated by proofs/export_patterns.py from
// shpreflight.danger.PATTERNS — DO NOT EDIT. Regenerate with:
//   python proofs/export_patterns.py

type patternDef struct {
	code     string
	severity string
	heads    []string
	flags    []string
	targets  []string
	message  string
	fix      string
}

// patternTable mirrors the Python danger table entry for entry.
var patternTable = []patternDef{
	{"RM-ROOT", "error", []string{"rm"}, []string{"-R", "-RF", "-Rf", "-f", "-fr", "-r", "-rf"}, []string{"$HOME", "$HOME/", "$PWD", "%SYSTEMROOT%", "*", ".", "..", "/", "/*", "C:/", "C:\\", "C:\\Windows", "~", "~/*"}, "recursive force-delete aimed at a root/home/glob path", "restrict the target path; verify with --dry-run or -WhatIf"},
	{"RM-RECURSIVE", "warning", []string{"rm"}, []string{"-R", "-RF", "-Rf", "-fr", "-r", "-rf"}, nil, "recursive delete — irreversible without a trash can", "list the target first, or use a git-tracked directory"},
	{"REMOVE-ITEM-RECURSE-FORCE", "warning", []string{"Remove-Item", "del", "erase", "rd", "ri"}, []string{"-Force", "-Recurse", "/f", "/q", "/s"}, nil, "recursive/forced removal (Remove-Item -Recurse -Force or del /s /q)", "add -WhatIf to preview what would be removed"},
	{"GIT-RESET-HARD", "warning", []string{"git"}, []string{"--hard"}, nil, "git reset --hard discards uncommitted work", "git stash first, or reset a specific path"},
	{"GIT-PUSH-FORCE", "warning", []string{"git"}, []string{"--force", "--force-with-lease", "-f"}, nil, "force push can overwrite upstream history", "prefer --force-with-lease and confirm the branch"},
	{"GIT-CLEAN-ND", "warning", []string{"git"}, []string{"-X", "-d", "-f", "-fd", "-fdx", "-x", "clean"}, nil, "git clean removes untracked files permanently", "run 'git clean -n' first to preview"},
	{"SHUTDOWN", "error", []string{"halt", "poweroff", "reboot", "restart", "shutdown"}, nil, nil, "machine power state change", "confirm intent with the user before running"},
	{"FORMAT", "error", []string{"format", "mkfs", "mkfs.ext4", "mkfs.vfat"}, nil, nil, "filesystem format destroys all data on the volume", "never run this from an agent without explicit user confirmation"},
	{"DD-RAW", "error", []string{"dd"}, nil, []string{"/dev/disk0", "/dev/hda", "/dev/hdb", "/dev/mmcblk0", "/dev/nvme0n1", "/dev/nvme0n2", "/dev/nvme1n1", "/dev/nvme1n2", "/dev/rdisk0", "/dev/sda", "/dev/sdb", "/dev/sdc", "/dev/sdd", "/dev/sde", "/dev/sdf", "/dev/sdg", "/dev/sdh", "/dev/sdi", "/dev/sdj", "/dev/sdk", "/dev/sdl", "/dev/sdm", "/dev/sdn", "/dev/sdo", "/dev/sdp", "/dev/vda", "/dev/vdb", "/dev/vdc", "/dev/xvda", "/dev/xvdb", "\\\\.\\PhysicalDrive0", "\\\\.\\PhysicalDrive1", "of=/dev/disk0", "of=/dev/hda", "of=/dev/hdb", "of=/dev/mmcblk0", "of=/dev/nvme0n1", "of=/dev/nvme0n2", "of=/dev/nvme1n1", "of=/dev/nvme1n2", "of=/dev/rdisk0", "of=/dev/sda", "of=/dev/sdb", "of=/dev/sdc", "of=/dev/sdd", "of=/dev/sde", "of=/dev/sdf", "of=/dev/sdg", "of=/dev/sdh", "of=/dev/sdi", "of=/dev/sdj", "of=/dev/sdk", "of=/dev/sdl", "of=/dev/sdm", "of=/dev/sdn", "of=/dev/sdo", "of=/dev/sdp", "of=/dev/vda", "of=/dev/vdb", "of=/dev/vdc", "of=/dev/xvda", "of=/dev/xvdb", "of=\\\\.\\PhysicalDrive0", "of=\\\\.\\PhysicalDrive1"}, "dd targeting a raw device overwrites the disk", "verify of= points at a file, not a device"},
	{"CHMOD-777-ROOT", "error", []string{"chmod"}, nil, []string{"$HOME", "*", "/", "/*", "~", "~/*"}, "chmod applied to a root/home/glob path", "scope permissions to the actual project directory"},
	{"SHRED", "error", []string{"shred", "srm"}, nil, nil, "secure delete is irreversible", "confirm intent with the user"},
	{"TASKKILL-FORCE", "warning", []string{"taskkill"}, []string{"-f", "/f"}, nil, "taskkill /f terminates processes without cleanup", "drop /f if graceful termination is acceptable"},
	{"SET-EXECUTIONPOLICY", "warning", []string{"Set-ExecutionPolicy"}, []string{"-Force", "-Scope", "Bypass", "Process"}, nil, "loosens the PowerShell execution policy", "scope it to -Scope Process if unavoidable"},
	{"TRUNCATE", "warning", []string{"truncate"}, nil, nil, "truncate empties files in place", "confirm the target file is disposable"},
}
