/* Generated by proofs/export_patterns.py from
   shpreflight.danger.PATTERNS — DO NOT EDIT. Regenerate with:
   python proofs/export_patterns.py */
#ifndef SHPREFLIGHT_PATTERNS_GEN_H
#define SHPREFLIGHT_PATTERNS_GEN_H

#include <stddef.h>

typedef struct {
	const char *code;
	const char *severity;
	const char *const *heads;
	size_t heads_len;
	const char *const *flags;
	size_t flags_len;
	const char *const *targets;
	size_t targets_len;
	const char *message;
	const char *fix;
} PatternDef;

static const char *const p0_heads[] = {"rm"};
static const char *const p0_flags[] = {"-R", "-RF", "-Rf", "-f", "-fr", "-r", "-rf"};
static const char *const p0_targets[] = {"$HOME", "$HOME/", "$PWD", "%SYSTEMROOT%", "*", ".", "..", "/", "/*", "C:/", "C:\\", "C:\\Windows", "~", "~/*"};
static const char *const p1_heads[] = {"rm"};
static const char *const p1_flags[] = {"-R", "-RF", "-Rf", "-fr", "-r", "-rf"};
static const char *const p1_targets[] = {0};
static const char *const p2_heads[] = {"Remove-Item", "del", "erase", "rd", "ri"};
static const char *const p2_flags[] = {"-Force", "-Recurse", "/f", "/q", "/s"};
static const char *const p2_targets[] = {0};
static const char *const p3_heads[] = {"git"};
static const char *const p3_flags[] = {"--hard"};
static const char *const p3_targets[] = {0};
static const char *const p4_heads[] = {"git"};
static const char *const p4_flags[] = {"--force", "--force-with-lease", "-f"};
static const char *const p4_targets[] = {0};
static const char *const p5_heads[] = {"git"};
static const char *const p5_flags[] = {"-X", "-d", "-f", "-fd", "-fdx", "-x", "clean"};
static const char *const p5_targets[] = {0};
static const char *const p6_heads[] = {"halt", "poweroff", "reboot", "restart", "shutdown"};
static const char *const p6_flags[] = {0};
static const char *const p6_targets[] = {0};
static const char *const p7_heads[] = {"format", "mkfs", "mkfs.ext4", "mkfs.vfat"};
static const char *const p7_flags[] = {0};
static const char *const p7_targets[] = {0};
static const char *const p8_heads[] = {"dd"};
static const char *const p8_flags[] = {0};
static const char *const p8_targets[] = {"/dev/disk0", "/dev/hda", "/dev/hdb", "/dev/mmcblk0", "/dev/nvme0n1", "/dev/nvme0n2", "/dev/nvme1n1", "/dev/nvme1n2", "/dev/rdisk0", "/dev/sda", "/dev/sdb", "/dev/sdc", "/dev/sdd", "/dev/sde", "/dev/sdf", "/dev/sdg", "/dev/sdh", "/dev/sdi", "/dev/sdj", "/dev/sdk", "/dev/sdl", "/dev/sdm", "/dev/sdn", "/dev/sdo", "/dev/sdp", "/dev/vda", "/dev/vdb", "/dev/vdc", "/dev/xvda", "/dev/xvdb", "\\\\.\\PhysicalDrive0", "\\\\.\\PhysicalDrive1", "of=/dev/disk0", "of=/dev/hda", "of=/dev/hdb", "of=/dev/mmcblk0", "of=/dev/nvme0n1", "of=/dev/nvme0n2", "of=/dev/nvme1n1", "of=/dev/nvme1n2", "of=/dev/rdisk0", "of=/dev/sda", "of=/dev/sdb", "of=/dev/sdc", "of=/dev/sdd", "of=/dev/sde", "of=/dev/sdf", "of=/dev/sdg", "of=/dev/sdh", "of=/dev/sdi", "of=/dev/sdj", "of=/dev/sdk", "of=/dev/sdl", "of=/dev/sdm", "of=/dev/sdn", "of=/dev/sdo", "of=/dev/sdp", "of=/dev/vda", "of=/dev/vdb", "of=/dev/vdc", "of=/dev/xvda", "of=/dev/xvdb", "of=\\\\.\\PhysicalDrive0", "of=\\\\.\\PhysicalDrive1"};
static const char *const p9_heads[] = {"chmod"};
static const char *const p9_flags[] = {0};
static const char *const p9_targets[] = {"$HOME", "*", "/", "/*", "~", "~/*"};
static const char *const p10_heads[] = {"shred", "srm"};
static const char *const p10_flags[] = {0};
static const char *const p10_targets[] = {0};
static const char *const p11_heads[] = {"taskkill"};
static const char *const p11_flags[] = {"-f", "/f"};
static const char *const p11_targets[] = {0};
static const char *const p12_heads[] = {"Set-ExecutionPolicy"};
static const char *const p12_flags[] = {"-Force", "-Scope", "Bypass", "Process"};
static const char *const p12_targets[] = {0};
static const char *const p13_heads[] = {"truncate"};
static const char *const p13_flags[] = {0};
static const char *const p13_targets[] = {0};

static const PatternDef pattern_table[] = {
	{"RM-ROOT", "error", p0_heads, 1, p0_flags, 7, p0_targets, 14, "recursive force-delete aimed at a root/home/glob path", "restrict the target path; verify with --dry-run or -WhatIf"},
	{"RM-RECURSIVE", "warning", p1_heads, 1, p1_flags, 6, p1_targets, 0, "recursive delete — irreversible without a trash can", "list the target first, or use a git-tracked directory"},
	{"REMOVE-ITEM-RECURSE-FORCE", "warning", p2_heads, 5, p2_flags, 5, p2_targets, 0, "recursive/forced removal (Remove-Item -Recurse -Force or del /s /q)", "add -WhatIf to preview what would be removed"},
	{"GIT-RESET-HARD", "warning", p3_heads, 1, p3_flags, 1, p3_targets, 0, "git reset --hard discards uncommitted work", "git stash first, or reset a specific path"},
	{"GIT-PUSH-FORCE", "warning", p4_heads, 1, p4_flags, 3, p4_targets, 0, "force push can overwrite upstream history", "prefer --force-with-lease and confirm the branch"},
	{"GIT-CLEAN-ND", "warning", p5_heads, 1, p5_flags, 7, p5_targets, 0, "git clean removes untracked files permanently", "run 'git clean -n' first to preview"},
	{"SHUTDOWN", "error", p6_heads, 5, p6_flags, 0, p6_targets, 0, "machine power state change", "confirm intent with the user before running"},
	{"FORMAT", "error", p7_heads, 4, p7_flags, 0, p7_targets, 0, "filesystem format destroys all data on the volume", "never run this from an agent without explicit user confirmation"},
	{"DD-RAW", "error", p8_heads, 1, p8_flags, 0, p8_targets, 64, "dd targeting a raw device overwrites the disk", "verify of= points at a file, not a device"},
	{"CHMOD-777-ROOT", "error", p9_heads, 1, p9_flags, 0, p9_targets, 6, "chmod applied to a root/home/glob path", "scope permissions to the actual project directory"},
	{"SHRED", "error", p10_heads, 2, p10_flags, 0, p10_targets, 0, "secure delete is irreversible", "confirm intent with the user"},
	{"TASKKILL-FORCE", "warning", p11_heads, 1, p11_flags, 2, p11_targets, 0, "taskkill /f terminates processes without cleanup", "drop /f if graceful termination is acceptable"},
	{"SET-EXECUTIONPOLICY", "warning", p12_heads, 1, p12_flags, 4, p12_targets, 0, "loosens the PowerShell execution policy", "scope it to -Scope Process if unavoidable"},
	{"TRUNCATE", "warning", p13_heads, 1, p13_flags, 0, p13_targets, 0, "truncate empties files in place", "confirm the target file is disposable"},
};

#define PATTERN_TABLE_LEN 14

#endif /* SHPREFLIGHT_PATTERNS_GEN_H */
