/*
 * shpreflight.c — single-file C99 port of shpreflight: pre-flight
 * diagnostics for shell commands generated by AI agents (dialect
 * compatibility, missing tools, destructive operations — before the
 * command runs).
 *
 * Build (no third-party dependencies, C99 + libc only):
 *   POSIX (Linux/macOS):   cc -O2 -std=c99 -Wall -Wextra -o shpreflight shpreflight.c
 *   MinGW gcc on Windows:  gcc -O2 -std=c99 -Wall -Wextra -o shpreflight.exe shpreflight.c
 *   MSVC:                  cl /O2 /utf-8 shpreflight.c
 *
 * The danger pattern table is generated from the Python reference
 * (c/patterns_gen.h, regenerated by proofs/export_patterns.py), so the
 * Python, Go and C ports share one source of truth whose recall over the
 * table itself is machine-checked in Lean 4 (proofs/Shpreflight.lean).
 *
 * The lexer preserves the machine-checked conservation invariant: the
 * concatenation of all token texts equals the input command, so no
 * destructive fragment can hide in a lexing blind spot.
 *
 * Exit codes are machine-readable so agents can branch on them:
 *   0 ok, 1 warn, 2 fail, 3 usage error.
 *
 * Memory policy: one-shot CLI process — structures are allocated and never
 * freed (arena-style); the OS reclaims at exit. The embedded test binary
 * (c/test_shpreflight.c) exercises the same paths.
 */

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if defined(_WIN32)
#  define WIN32_LEAN_AND_MEAN
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#else
#  include <dirent.h>
#endif

#include "patterns_gen.h"

/* ================= allocation & string builders ================= */

static void *xmalloc(size_t n)
{
    void *p = malloc(n ? n : 1);
    if (!p) {
        fputs("shpreflight: out of memory\n", stderr);
        exit(4);
    }
    return p;
}

static char *xstrndup(const char *s, size_t n)
{
    char *p = xmalloc(n + 1);
    memcpy(p, s, n);
    p[n] = '\0';
    return p;
}

static char *xstrdup(const char *s) { return xstrndup(s, strlen(s)); }

static char *xasprintf(const char *fmt, ...)
{
    va_list ap;
    char stackbuf[512];
    int n;
    char *out;

    va_start(ap, fmt);
    n = vsnprintf(stackbuf, sizeof stackbuf, fmt, ap);
    va_end(ap);
    if (n < 0)
        return xstrdup("");
    out = xmalloc((size_t)n + 1);
    if ((size_t)n < sizeof stackbuf) {
        memcpy(out, stackbuf, (size_t)n + 1);
    } else {
        va_start(ap, fmt);
        vsnprintf(out, (size_t)n + 1, fmt, ap);
        va_end(ap);
    }
    return out;
}

typedef struct {
    char *p;
    size_t n, cap;
} Buf;

static void buf_reserve(Buf *b, size_t extra)
{
    if (b->n + extra + 1 > b->cap) {
        size_t want = b->cap ? b->cap * 2 : 128;
        while (want < b->n + extra + 1)
            want *= 2;
        b->p = realloc(b->p, want);
        if (!b->p) {
            fputs("shpreflight: out of memory\n", stderr);
            exit(4);
        }
        b->cap = want;
    }
}

static void buf_add(Buf *b, const char *s, size_t n)
{
    buf_reserve(b, n);
    memcpy(b->p + b->n, s, n);
    b->n += n;
    b->p[b->n] = '\0';
}

static void buf_addcstr(Buf *b, const char *s) { buf_add(b, s, strlen(s)); }
static void buf_addch(Buf *b, char c) { buf_add(b, &c, 1); }

/* borrowed byte slice: p points into a buffer that outlives all uses */
typedef struct {
    const char *p;
    size_t n;
} Str;

#define STR_ARGS(s) (int)(s).n, (s).p

#if defined(__GNUC__)
#define SHP_MAYBE_UNUSED __attribute__((unused))
#else
#define SHP_MAYBE_UNUSED
#endif

static int str_eq(Str a, Str b) SHP_MAYBE_UNUSED;

static int str_eq(Str a, Str b)
{
    return a.n == b.n && (a.n == 0 || memcmp(a.p, b.p, a.n) == 0);
}

static int str_eq_cstr(Str a, const char *s)
{
    size_t n = strlen(s);
    return a.n == n && (n == 0 || memcmp(a.p, s, n) == 0);
}

static int str_contains_ch(Str a, char c)
{
    return a.n > 0 && memchr(a.p, c, a.n) != NULL;
}

static int str_endswith_cstr(Str a, const char *suffix)
{
    size_t n = strlen(suffix);
    return a.n >= n && memcmp(a.p + a.n - n, suffix, n) == 0;
}

static int str_isdigit(Str a)
{
    if (a.n == 0)
        return 0;
    for (size_t i = 0; i < a.n; i++)
        if (a.p[i] < '0' || a.p[i] > '9')
            return 0;
    return 1;
}

/* ================= lexer ================= */

typedef enum {
    TOK_WORD,
    TOK_SEP,
    TOK_OP,
    TOK_SQUOTE,
    TOK_DQUOTE,
    TOK_BACKTICK
} TokKind;

typedef struct {
    TokKind kind;
    Str text;
} Token;

typedef struct {
    Token *v;
    size_t n, cap;
} Tokens;

static void tokens_push(Tokens *t, TokKind kind, const char *p, size_t n)
{
    if (t->n == t->cap) {
        t->cap = t->cap ? t->cap * 2 : 16;
        t->v = realloc(t->v, t->cap * sizeof *t->v);
        if (!t->v) {
            fputs("shpreflight: out of memory\n", stderr);
            exit(4);
        }
    }
    t->v[t->n].kind = kind;
    t->v[t->n].text.p = p;
    t->v[t->n].text.n = n;
    t->n++;
}

static int is_ws_ch(char c)
{
    return c == ' ' || c == '\t' || c == '\r' || c == '\n';
}

static int is_op_ch(char c)
{
    return c == '&' || c == '|' || c == ';' || c == '<' || c == '>';
}

static int is_quote_ch(char c)
{
    return c == '\'' || c == '"' || c == '`';
}

/* span of a quoted region: [i, j) including both quotes when closed */
static size_t quoted_span(const char *cmd, size_t n, size_t i)
{
    const char *hit = memchr(cmd + i + 1, cmd[i], n - i - 1);
    return hit ? (size_t)(hit - cmd) + 1 : n;
}

/* Single-pass lexer. Every input byte lands in exactly one token. */
static void lex(const char *cmd, size_t n, Tokens *out)
{
    size_t i = 0;
    while (i < n) {
        char ch = cmd[i];
        if (is_ws_ch(ch)) {
            size_t j = i + 1;
            while (j < n && is_ws_ch(cmd[j]))
                j++;
            tokens_push(out, TOK_SEP, cmd + i, j - i);
            i = j;
        } else if (is_quote_ch(ch)) {
            TokKind k = ch == '\'' ? TOK_SQUOTE : (ch == '"' ? TOK_DQUOTE : TOK_BACKTICK);
            size_t j = quoted_span(cmd, n, i);
            tokens_push(out, k, cmd + i, j - i);
            i = j;
        } else if (is_op_ch(ch)) {
            size_t j = i + 1;
            while (j < n && is_op_ch(cmd[j]))
                j++;
            tokens_push(out, TOK_OP, cmd + i, j - i);
            i = j;
        } else {
            size_t j = i + 1;
            while (j < n && !is_op_ch(cmd[j]) && !is_ws_ch(cmd[j]) && !is_quote_ch(cmd[j]))
                j++;
            tokens_push(out, TOK_WORD, cmd + i, j - i);
            i = j;
        }
    }
}

static int tok_is_closed(const Token *t)
{
    if (t->kind != TOK_SQUOTE && t->kind != TOK_DQUOTE && t->kind != TOK_BACKTICK)
        return 1;
    return t->text.n >= 2 && t->text.p[0] == t->text.p[t->text.n - 1];
}

/* conservation invariant: concat(token texts) == cmd (used by the tests) */
static int reconstruct_eq(const Tokens *t, const char *cmd, size_t n) SHP_MAYBE_UNUSED;
static int reconstruct_eq(const Tokens *t, const char *cmd, size_t n)
{
    size_t pos = 0;
    for (size_t i = 0; i < t->n; i++) {
        if (pos + t->v[i].text.n > n || memcmp(cmd + pos, t->v[i].text.p, t->v[i].text.n) != 0)
            return 0;
        pos += t->v[i].text.n;
    }
    return pos == n;
}

/* ================= segments ================= */

typedef struct {
    Str head;         /* valid when has_head */
    int has_head;
    Str *words;       /* quote-stripped, owned array of borrowed slices */
    size_t nwords;
    Str *redirects;
    size_t nredirects;
    const char *terminator; /* "|", "||", ";", "&&", "&" or NULL */
} Segment;

typedef struct {
    Segment *v;
    size_t n, cap;
} Segments;

static int seg_pipes_out(const Segment *s)
{
    return s->terminator != NULL && strcmp(s->terminator, "|") == 0;
}

static int is_control_op(Str text)
{
    static const char *const ops[] = {"|", "||", ";", "&&", "&"};
    for (size_t i = 0; i < sizeof ops / sizeof ops[0]; i++)
        if (str_eq_cstr(text, ops[i]))
            return 1;
    return 0;
}

static Str strip_quotes(Str w)
{
    if (w.n >= 2 && is_quote_ch(w.p[0]) && w.p[0] == w.p[w.n - 1])
        return (Str){ w.p + 1, w.n - 2 };
    return w;
}

typedef struct {
    Segments *out;
    Str *words;
    size_t nwords, capwords;
    Str *redirects;
    size_t nredirs, capredirs;
    size_t raw_len;
    int in_redirect;
} SegState;

static void seg_flush(SegState *st, const char *terminator)
{
    if (st->nwords > 0 || st->nredirs > 0 || st->raw_len > 0) {
        Segment s;
        memset(&s, 0, sizeof s);
        s.has_head = st->nwords > 0;
        if (s.has_head)
            s.head = st->words[0];
        s.nwords = st->nwords;
        if (st->nwords > 0) {
            s.words = xmalloc(st->nwords * sizeof(Str));
            memcpy(s.words, st->words, st->nwords * sizeof(Str));
        }
        s.nredirects = st->nredirs;
        if (st->nredirs > 0) {
            s.redirects = xmalloc(st->nredirs * sizeof(Str));
            memcpy(s.redirects, st->redirects, st->nredirs * sizeof(Str));
        }
        s.terminator = terminator;
        if (st->out->n == st->out->cap) {
            st->out->cap = st->out->cap ? st->out->cap * 2 : 8;
            st->out->v = realloc(st->out->v, st->out->cap * sizeof(Segment));
            if (!st->out->v) {
                fputs("shpreflight: out of memory\n", stderr);
                exit(4);
            }
        }
        st->out->v[st->out->n++] = s;
    }
    st->nwords = 0;
    st->nredirs = 0;
    st->raw_len = 0;
    /* redirect state is per-segment: without this reset, every word after
       "x > f && ..." would be swallowed as a redirect target and the head
       of the next segment (e.g. an "rm -rf /") would vanish from analysis */
    st->in_redirect = 0;
}

static void seg_state_push_word(Str **arr, size_t *n, size_t *cap, Str w)
{
    if (*n == *cap) {
        *cap = *cap ? *cap * 2 : 8;
        *arr = realloc(*arr, *cap * sizeof(Str));
        if (!*arr) {
            fputs("shpreflight: out of memory\n", stderr);
            exit(4);
        }
    }
    (*arr)[(*n)++] = w;
}

static void split_segments(const Tokens *toks, Segments *out)
{
    SegState st;
    memset(&st, 0, sizeof st);
    st.out = out;

    for (size_t i = 0; i < toks->n; i++) {
        const Token *t = &toks->v[i];
        switch (t->kind) {
        case TOK_SEP:
            st.raw_len += t->text.n;
            break;
        case TOK_OP:
            st.raw_len += t->text.n;
            if (is_control_op(t->text))
                seg_flush(&st, xstrndup(t->text.p, t->text.n));
            else
                st.in_redirect = 1;
            break;
        default: { /* WORD, SQUOTE, DQUOTE, BACKTICK */
            Str bare = strip_quotes(t->text);
            st.raw_len += t->text.n;
            const Token *nxt = (i + 1 < toks->n) ? &toks->v[i + 1] : NULL;
            if (t->kind == TOK_WORD && str_isdigit(bare) && nxt &&
                nxt->kind == TOK_OP &&
                (str_contains_ch(nxt->text, '>') || str_contains_ch(nxt->text, '<'))) {
                /* fd prefix of the next redirect: "out 2> err", "log 2>&1" */
                continue;
            }
            if (st.in_redirect)
                seg_state_push_word(&st.redirects, &st.nredirs, &st.capredirs, bare);
            else
                seg_state_push_word(&st.words, &st.nwords, &st.capwords, bare);
            break;
        }
        }
    }
    seg_flush(&st, NULL);
}

/* ================= shell registry ================= */

typedef struct {
    const char *key;
    const char *desc;
} ShellDef;

static const ShellDef shell_table[] = {
    { "powershell5", "Windows PowerShell 5.1 (powershell.exe)" },
    { "pwsh7", "PowerShell 7+ (pwsh.exe)" },
    { "bash", "Bash (Git Bash / WSL / Unix)" },
    { "cmd", "Windows cmd.exe" },
    { "sh", "POSIX sh" },
};
#define SHELL_TABLE_LEN (sizeof shell_table / sizeof shell_table[0])

static const char *default_shell(void)
{
#if defined(_WIN32)
    return "powershell5";
#else
    return "bash";
#endif
}

/* 0 = ok, nonzero = unknown shell (message in *errmsg) */
static int resolve_target(const char *shell, const char **out, const char **errmsg)
{
    if (!shell || !*shell || strcmp(shell, "auto") == 0) {
        *out = default_shell();
        return 0;
    }
    for (size_t i = 0; i < SHELL_TABLE_LEN; i++) {
        if (strcmp(shell_table[i].key, shell) == 0) {
            *out = shell_table[i].key;
            return 0;
        }
    }
    *errmsg = xasprintf("unknown shell '%s'; see `shpreflight shells`", shell);
    return 1;
}

static int is_powershell(const char *target)
{
    return strcmp(target, "powershell5") == 0 || strcmp(target, "pwsh7") == 0;
}

static int is_windows_shell(const char *target)
{
    return is_powershell(target) || strcmp(target, "cmd") == 0;
}

/* ================= issues ================= */

typedef struct {
    const char *code;
    const char *severity; /* "error" | "warning" | "info" */
    const char *kind;     /* "syntax" | "danger" | "tool" */
    char *message;        /* owned */
    const char *fix;      /* static or NULL */
    const char *tool;     /* static or NULL */
} Issue;

typedef struct {
    Issue *v;
    size_t n, cap;
} Issues;

static void issues_push(Issues *iss, const char *code, const char *severity,
                        const char *kind, const char *message,
                        const char *fix, const char *tool)
{
    if (iss->n == iss->cap) {
        iss->cap = iss->cap ? iss->cap * 2 : 16;
        iss->v = realloc(iss->v, iss->cap * sizeof(Issue));
        if (!iss->v) {
            fputs("shpreflight: out of memory\n", stderr);
            exit(4);
        }
    }
    Issue *it = &iss->v[iss->n++];
    it->code = code;
    it->severity = severity;
    it->kind = kind;
    it->message = xstrdup(message);
    it->fix = fix;
    it->tool = tool;
}

#if PATTERN_TABLE_LEN > 64
#error "hit_codes in check_danger is fixed-size: raise the limit or reallocate"
#endif

/* ================= danger detection ================= */

static const char *const shell_heads[] = {
    "sh", "bash", "zsh", "pwsh", "powershell", "dash"
};
#define SHELL_HEADS_LEN (sizeof shell_heads / sizeof shell_heads[0])

static const char *const exec_heads[] = { "iex", "Invoke-Expression", "eval" };
#define EXEC_HEADS_LEN (sizeof exec_heads / sizeof exec_heads[0])

static const char *const sensitive_bases[] = {
    ".env", ".env.local", ".env.production", "secrets",
    "id_rsa", "id_ed25519", "credentials", "credentials.json",
    ".npmrc", ".netrc", ".aws/credentials"
};
#define SENSITIVE_BASES_LEN (sizeof sensitive_bases / sizeof sensitive_bases[0])

static int str_in_cstr_list(Str w, const char *const *list, size_t n)
{
    for (size_t i = 0; i < n; i++)
        if (str_eq_cstr(w, list[i]))
            return 1;
    return 0;
}

static int wordlist_has(const Str *words, size_t n, const char *s)
{
    for (size_t i = 0; i < n; i++)
        if (str_eq_cstr(words[i], s))
            return 1;
    return 0;
}

static int any_word_in_list(const Str *words, size_t n,
                            const char *const *list, size_t ln)
{
    for (size_t i = 0; i < n; i++)
        for (size_t j = 0; j < ln; j++)
            if (str_eq_cstr(words[i], list[j]))
                return 1;
    return 0;
}

/* structural match: head, then any-of flags, then any-of targets */
static int match_pattern(const Str *words, size_t n, const PatternDef *p)
{
    if (n == 0)
        return 0;
    if (!str_in_cstr_list(words[0], p->heads, p->heads_len))
        return 0;
    const Str *rest = words + 1;
    size_t restn = n - 1;
    if (p->flags_len > 0 && !any_word_in_list(rest, restn, p->flags, p->flags_len))
        return 0;
    if (p->targets_len > 0 && !any_word_in_list(rest, restn, p->targets, p->targets_len))
        return 0;
    return 1;
}

/* basename across both separator conventions: rsplit on '/', then on '\\',
   equals the span after the later of the two separators */
static Str path_basename(Str path)
{
    const char *last = NULL;
    for (size_t i = 0; i < path.n; i++) {
        if (path.p[i] == '/' || path.p[i] == '\\')
            last = path.p + i;
    }
    if (!last)
        return path;
    return (Str){ last + 1, path.n - (size_t)(last - path.p) - 1 };
}

static void check_danger(const Segments *segs, Issues *out)
{
    int pipe_receiver = 0;
    for (size_t si = 0; si < segs->n; si++) {
        const Segment *seg = &segs->v[si];
        if (seg->has_head) {
            Str head = seg->head;
            if (pipe_receiver &&
                (str_in_cstr_list(head, shell_heads, SHELL_HEADS_LEN) ||
                 str_in_cstr_list(head, exec_heads, EXEC_HEADS_LEN))) {
                char *msg = xasprintf(
                    "pipe feeds untrusted input into '%.*s' — remote-code-execution "
                    "pattern (curl ... | sh)", STR_ARGS(head));
                issues_push(out, "PIPE-EXEC", "error", "danger", msg,
                            "download first, inspect, then run", NULL);
            }
            if (pipe_receiver && str_eq_cstr(head, "npm") &&
                wordlist_has(seg->words, seg->nwords, "publish")) {
                issues_push(out, "NPM-PUBLISH", "warning", "danger",
                            "publishing to the npm registry makes the package public",
                            "use npm publish --dry-run until content is final", NULL);
            }
        }
        const char *hit_codes[64];
        size_t nhit = 0;
        for (size_t pi = 0; pi < PATTERN_TABLE_LEN; pi++) {
            const PatternDef *p = &pattern_table[pi];
            if (!match_pattern(seg->words, seg->nwords, p))
                continue;
            /* RM-ROOT already says everything about this segment's rm */
            int root_hit = 0;
            for (size_t h = 0; h < nhit; h++)
                if (strcmp(hit_codes[h], "RM-ROOT") == 0)
                    root_hit = 1;
            if (strcmp(p->code, "RM-RECURSIVE") == 0 && root_hit)
                continue;
            if (nhit < sizeof hit_codes / sizeof hit_codes[0])
                hit_codes[nhit++] = p->code;
            char *msg = xasprintf("%.*s: %s", (int)seg->words[0].n,
                                  seg->words[0].p, p->message);
            issues_push(out, p->code, p->severity, "danger", msg, p->fix, NULL);
        }
        for (size_t ri = 0; ri < seg->nredirects; ri++) {
            Str redir = seg->redirects[ri];
            if (str_in_cstr_list(path_basename(redir), sensitive_bases, SENSITIVE_BASES_LEN) ||
                str_endswith_cstr(redir, ".key") || str_endswith_cstr(redir, ".pem")) {
                char *msg = xasprintf(
                    "overwriting sensitive file '%.*s' via redirection",
                    STR_ARGS(redir));
                issues_push(out, "REDIR-SENSITIVE", "warning", "danger", msg,
                            "write to a temp file and diff first", NULL);
            }
        }
        pipe_receiver = seg_pipes_out(seg);
    }
}

/* ================= dialect rules ================= */

static int is_letter(char c)
{
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
}

static int is_ident_start(char c) { return c == '_' || is_letter(c); }

static int is_ident_char(char c) { return is_ident_start(c) || (c >= '0' && c <= '9'); }

/* fullmatch \$[A-Za-z_][A-Za-z0-9_]*$ — a bare bash variable */
static int var_re(Str s)
{
    if (s.n < 2 || s.p[0] != '$' || !is_ident_start(s.p[1]))
        return 0;
    for (size_t i = 2; i < s.n; i++)
        if (!is_ident_char(s.p[i]))
            return 0;
    return 1;
}

/* fullmatch \$\{[A-Za-z_][A-Za-z0-9_]*\}$ */
static int brace_var_re(Str s)
{
    if (s.n < 4 || s.p[0] != '$' || s.p[1] != '{' || s.p[s.n - 1] != '}')
        return 0;
    if (!is_ident_start(s.p[2]))
        return 0;
    for (size_t i = 3; i + 1 < s.n; i++)
        if (!is_ident_char(s.p[i]))
            return 0;
    return 1;
}

/* fullmatch [A-Z][A-Za-z]+-[A-Z][A-Za-z]+$ — a PowerShell cmdlet name */
static int cmlet_re(Str s)
{
    if (s.n < 5 || s.p[0] < 'A' || s.p[0] > 'Z')
        return 0;
    size_t i = 1, letters = 0;
    while (i < s.n && is_letter(s.p[i])) {
        i++;
        letters++;
    }
    if (letters == 0 || i >= s.n || s.p[i] != '-')
        return 0;
    i++;
    if (i >= s.n || s.p[i] < 'A' || s.p[i] > 'Z')
        return 0;
    i++;
    letters = 0;
    while (i < s.n && is_letter(s.p[i])) {
        i++;
        letters++;
    }
    return i == s.n && letters > 0;
}

/* re.match(r"^-[a-zA-Z]+|^--[a-zA-Z-]+$"): curl-style flags */
static int curl_flags(Str w)
{
    if (w.n >= 2 && w.p[0] == '-' && w.p[1] == '-') {
        if (w.n == 2)
            return 0;
        for (size_t i = 2; i < w.n; i++)
            if (!is_letter(w.p[i]) && w.p[i] != '-')
                return 0;
        return 1;
    }
    if (w.n >= 2 && w.p[0] == '-')
        return is_letter(w.p[1]);
    return 0;
}

static const char *const special_vars[] = {
    "$?", "$!", "$$", "$#", "$@", "$*",
    "$0", "$1", "$2", "$3", "$4", "$5", "$6", "$7", "$8", "$9"
};
#define SPECIAL_VARS_LEN (sizeof special_vars / sizeof special_vars[0])

static const char *const rm_short_flags[] = { "-r", "-f", "-rf", "-fr", "-Rf", "-R" };
#define RM_SHORT_FLAGS_LEN (sizeof rm_short_flags / sizeof rm_short_flags[0])

/* POSIX commands with no Windows PowerShell 5.1 equivalent alias, plus the
   native replacement agents should switch to. */
typedef struct {
    const char *name;
    const char *replacement;
} PosixToPs;

static const PosixToPs posix_to_ps[] = {
    { "grep", "Select-String (sls)" },
    { "sed", "-replace operator" },
    { "awk", "ForEach-Object + split" },
    { "find", "Get-ChildItem -Recurse" },
    { "head", "Select-Object -First N" },
    { "tail", "Get-Content -Tail N" },
    { "touch", "New-Item -ItemType File" },
    { "chmod", "icacls" },
    { "chown", "icacls" },
    { "which", "Get-Command" },
    { "xargs", "ForEach-Object" },
    { "df", "Get-PSDrive" },
    { "du", "Get-ChildItem -Recurse | Measure-Object Length -Sum" },
    { "wc", "Measure-Object -Line/-Word/-Character" },
    { "tr", "-replace / .ToLower" },
    { "cut", ".Split()" },
    { "uniq", "Select-Object -Unique" },
    { "uname", "$env:OS" },
    { "env", "Get-ChildItem env:" },
    { "basename", "Split-Path -Leaf" },
    { "dirname", "Split-Path -Parent" },
    { "ln", "New-Item -ItemType SymbolicLink" },
    { "readlink", "(Get-Item).Target" },
    { "mktemp", "New-TemporaryFile" },
    { "stat", "Get-Item" },
    { "less", "more.com / Out-Host -Paging" },
    { "open", "Start-Process (alias on macOS only)" },
    { "make", "external: install via winget" },
};
#define POSIX_TO_PS_LEN (sizeof posix_to_ps / sizeof posix_to_ps[0])

static const char *posix_replacement_for(Str head)
{
    for (size_t i = 0; i < POSIX_TO_PS_LEN; i++)
        if (str_eq_cstr(head, posix_to_ps[i].name))
            return posix_to_ps[i].replacement;
    return NULL;
}

/* renders s the way Python's repr() would (ASCII input) */
static void py_repr(Str s, size_t maxlen, Buf *out)
{
    Str t = s.n > maxlen ? (Str){ s.p, maxlen } : s;
    int has_single = str_contains_ch(t, '\'');
    int has_double = str_contains_ch(t, '"');
    char q = '\'';
    if (has_single && !has_double)
        q = '"';
    buf_addch(out, q);
    for (size_t i = 0; i < t.n; i++) {
        char c = t.p[i];
        if (c == '\\') {
            buf_addcstr(out, "\\\\");
        } else if (c == '\n') {
            buf_addcstr(out, "\\n");
        } else if (c == '\t') {
            buf_addcstr(out, "\\t");
        } else if (c == '\r') {
            buf_addcstr(out, "\\r");
        } else if (c == q) {
            buf_addch(out, '\\');
            buf_addch(out, c);
        } else {
            buf_addch(out, c);
        }
    }
    buf_addch(out, q);
}

static void check_dialect(const Tokens *toks, const Segments *segs,
                          const char *target, Issues *out)
{
    int ps = is_powershell(target);
    int win = is_windows_shell(target);
    int on_bash = strcmp(target, "bash") == 0 || strcmp(target, "sh") == 0;
    int ps_or_cmd = ps || strcmp(target, "cmd") == 0;

    for (size_t i = 0; i < toks->n; i++) {
        const Token *t = &toks->v[i];
        if ((t->kind == TOK_SQUOTE || t->kind == TOK_DQUOTE || t->kind == TOK_BACKTICK) &&
            !tok_is_closed(t)) {
            Buf m;
            memset(&m, 0, sizeof m);
            buf_addcstr(&m, "unclosed quote starting at ");
            py_repr(t->text, 12, &m);
            buf_addcstr(&m, " — the shell will hang or fail");
            issues_push(out, "UNCLOSED-QUOTE", "error", "syntax", m.p,
                        "close the quote", NULL);
        }
    }

    for (size_t i = 0; i < toks->n; i++) {
        const Token *t = &toks->v[i];
        if (t->kind == TOK_OP) {
            if (str_eq_cstr(t->text, "&&") &&
                (strcmp(target, "powershell5") == 0 || strcmp(target, "cmd") == 0)) {
                issues_push(out, "SEP-AND", "error", "syntax",
                            "operator '&&' is not supported in this shell",
                            "separate commands, or chain with ';' if order alone matters",
                            NULL);
            } else if (str_eq_cstr(t->text, "||") &&
                       (strcmp(target, "powershell5") == 0 || strcmp(target, "cmd") == 0)) {
                issues_push(out, "SEP-OR", "error", "syntax",
                            "operator '||' is not supported in this shell",
                            "separate commands and check exit codes explicitly", NULL);
            }
        } else if (t->kind == TOK_WORD) {
            Str text = t->text;
            if (str_eq_cstr(text, "/dev/null") && win) {
                issues_push(out, "REDIR-DEVNULL", "error", "syntax",
                            "redirection to /dev/null — path does not exist on Windows",
                            "redirect to NUL instead:  2>NUL", NULL);
            } else if (ps_or_cmd && var_re(text)) {
                char *msg = xasprintf(
                    "bash-style variable %.*s — PowerShell reads it as an unset PS variable",
                    STR_ARGS(text));
                char *fix = xasprintf("use the environment: $env:%.*s",
                                      (int)(text.n - 1), text.p + 1);
                issues_push(out, "ENV-VAR", "error", "syntax", msg, fix, NULL);
            } else if (ps && brace_var_re(text)) {
                char *fix = xasprintf("use $env:%.*s", (int)(text.n - 3), text.p + 2);
                issues_push(out, "BRACE-VAR", "error", "syntax",
                            "bash-style ${var} expansion is not PowerShell syntax",
                            fix, NULL);
            } else if (ps && str_in_cstr_list(text, special_vars, SPECIAL_VARS_LEN)) {
                char *msg = xasprintf(
                    "%.*s means one thing in bash and another in PowerShell "
                    "(e.g. bash $? is the numeric exit code, PS $? is a bool)",
                    STR_ARGS(text));
                issues_push(out, "SPECIAL-VAR", "error", "syntax", msg,
                            "use $LASTEXITCODE for native exit codes", NULL);
            } else if (str_eq_cstr(text, "export") && ps_or_cmd) {
                issues_push(out, "EXPORT", "error", "syntax",
                            "'export' is not available in this shell",
                            "PowerShell: $env:NAME = \"value\"   cmd: set NAME=value", NULL);
            } else if (str_eq_cstr(text, "source") && ps) {
                issues_push(out, "SOURCE", "error", "syntax",
                            "'source' is not available in PowerShell",
                            "dot-source it:  . ./script.ps1", NULL);
            }
        } else if (t->kind == TOK_BACKTICK && ps_or_cmd) {
            issues_push(out, "BACKTICK", "error", "syntax",
                        "backticks mean command substitution in bash but are the escape "
                        "character in PowerShell — the command will do something else entirely",
                        "use $(...) for subexpressions in PowerShell", NULL);
        }
    }

    for (size_t si = 0; si < segs->n; si++) {
        const Segment *seg = &segs->v[si];
        if (!seg->has_head)
            continue;
        Str head = seg->head;
        const Str *rest = seg->words + 1;
        size_t restn = seg->nwords - 1;
        if (ps && str_eq_cstr(head, "curl")) {
            int any = 0;
            for (size_t i = 0; i < restn; i++)
                if (curl_flags(rest[i])) {
                    any = 1;
                    break;
                }
            if (any) {
                issues_push(out, "CURL-ALIAS", "error", "tool",
                            "'curl' is an alias for Invoke-WebRequest in Windows PowerShell 5.1 "
                            "and rejects unix curl flags",
                            "call the real binary: curl.exe -sL ...", NULL);
            }
        }
        if (ps && (str_eq_cstr(head, "rm") || str_eq_cstr(head, "del") ||
                   str_eq_cstr(head, "erase") || str_eq_cstr(head, "rd")) &&
            any_word_in_list(rest, restn, rm_short_flags, RM_SHORT_FLAGS_LEN)) {
            char *msg = xasprintf(
                "'%.*s' maps to Remove-Item in PowerShell, which has no -r/-f short flags",
                STR_ARGS(head));
            issues_push(out, "RM-FLAGS", "error", "syntax", msg,
                        "Remove-Item -Recurse -Force", NULL);
        }
        if (on_bash && cmlet_re(head)) {
            char *msg = xasprintf("'%.*s' is a PowerShell cmdlet; it does not exist in %s",
                                  STR_ARGS(head), target);
            issues_push(out, "CMDLET-IN-POSIX", "error", "tool", msg,
                        "use the POSIX equivalent for this shell", NULL);
        }
        if (win) {
            const char *repl = posix_replacement_for(head);
            if (repl) {
                char *msg = xasprintf("'%.*s' is not a Windows PowerShell command",
                                      STR_ARGS(head));
                issues_push(out, "POSIX-CMD", "error", "tool", msg, repl,
                            xstrndup(head.p, head.n));
            }
        }
    }
}

/* ================= PATH tool resolution ================= */

/* shell builtins and Windows internal commands, kept sorted for bsearch */
static const char *const builtins[] = {
    "alias", "break", "call", "case", "cd", "chdir", "cls", "color",
    "copy", "declare", "del", "dir", "do", "done", "echo", "elif",
    "else", "endlocal", "erase", "esac", "eval", "exec", "exit",
    "export", "false", "fi", "for", "function", "if", "in", "local",
    "md", "mkdir", "move", "popd", "prompt", "pushd", "rd", "read",
    "readonly", "ren", "return", "rmdir", "set", "setlocal", "shift",
    "source", "start", "then", "title", "trap", "true", "type",
    "unset", "ver", "vol", "while", "xcopy"
};
#define BUILTINS_LEN (sizeof builtins / sizeof builtins[0])

static int cmp_cstr(const void *a, const void *b)
{
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

static int is_builtin(const char *name)
{
    return bsearch(&name, builtins, BUILTINS_LEN, sizeof builtins[0], cmp_cstr) != NULL;
}

typedef struct {
    char **v;
    size_t n, cap;
} NameVec;

static void names_push(NameVec *nv, const char *s, size_t len)
{
    if (nv->n == nv->cap) {
        nv->cap = nv->cap ? nv->cap * 2 : 256;
        nv->v = realloc(nv->v, nv->cap * sizeof(char *));
        if (!nv->v) {
            fputs("shpreflight: out of memory\n", stderr);
            exit(4);
        }
    }
    nv->v[nv->n++] = xstrndup(s, len);
}

/* reset the PATH cache (used by the embedded test to swap PATH) */
void shp_tools_reset(void);
static NameVec path_cache;
static int path_cache_built;

void shp_tools_reset(void)
{
    path_cache.n = 0;
    path_cache_built = 0;
}

static const char *const win_exts[] = { ".exe", ".cmd", ".bat", ".com" };
#define WIN_EXTS_LEN (sizeof win_exts / sizeof win_exts[0])

#if defined(_WIN32)
static void scan_dir(const char *dir, NameVec *nv)
{
    size_t dn = strlen(dir);
    char pattern[1024];
    if (dn + 3 >= sizeof pattern)
        return;
    memcpy(pattern, dir, dn);
    size_t end = dn;
    if (end == 0 || (dir[end - 1] != '\\' && dir[end - 1] != '/'))
        pattern[end++] = '\\';
    pattern[end++] = '*';
    pattern[end] = '\0';

    WIN32_FIND_DATAA fd;
    HANDLE h = FindFirstFileA(pattern, &fd);
    if (h == INVALID_HANDLE_VALUE)
        return;
    do {
        const char *name = fd.cFileName;
        if (strcmp(name, ".") == 0 || strcmp(name, "..") == 0)
            continue;
        size_t n = strlen(name);
        names_push(nv, name, n);
        for (size_t e = 0; e < WIN_EXTS_LEN; e++) {
            size_t el = strlen(win_exts[e]);
            if (n > el && strcmp(name + n - el, win_exts[e]) == 0) {
                names_push(nv, name, n - el);
                break;
            }
        }
    } while (FindNextFileA(h, &fd));
    FindClose(h);
}
#else
static void scan_dir(const char *dir, NameVec *nv)
{
    DIR *d = opendir(dir);
    if (!d)
        return;
    struct dirent *ent;
    while ((ent = readdir(d)) != NULL) {
        const char *name = ent->d_name;
        if (strcmp(name, ".") == 0 || strcmp(name, "..") == 0)
            continue;
        names_push(nv, name, strlen(name));
    }
    closedir(d);
}
#endif

static int name_cmp(const void *a, const void *b)
{
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

static int name_in_cache(const char *name)
{
    return bsearch(&name, path_cache.v, path_cache.n, sizeof(char *), name_cmp) != NULL;
}

/* one ReadDir pass over PATH; lookups after that are membership tests */
static void build_path_cache(void)
{
    const char *path = getenv("PATH");
    if (!path)
        path = "";

    const char *sep = ",";
#if defined(_WIN32)
    sep = ";";
#else
    sep = ":";
#endif

    const char *p = path;
    for (;;) {
        const char *hit = strstr(p, sep);
        size_t len = hit ? (size_t)(hit - p) : strlen(p);
        if (len > 0) {
            char *dir = xstrndup(p, len);
            scan_dir(dir, &path_cache);
        }
        if (!hit)
            break;
        p = hit + strlen(sep);
    }
    qsort(path_cache.v, path_cache.n, sizeof(char *), name_cmp);
    path_cache_built = 1;
}

typedef struct {
    char *name;         /* owned */
    const char *status; /* "found" | "missing" */
    char *path;         /* name when found, else NULL */
} ToolInfo;

typedef struct {
    ToolInfo *v;
    size_t n, cap;
} ToolInfos;

static void toolinfos_push(ToolInfos *ti, char *name, const char *status, char *path)
{
    if (ti->n == ti->cap) {
        ti->cap = ti->cap ? ti->cap * 2 : 8;
        ti->v = realloc(ti->v, ti->cap * sizeof(ToolInfo));
        if (!ti->v) {
            fputs("shpreflight: out of memory\n", stderr);
            exit(4);
        }
    }
    ti->v[ti->n].name = name;
    ti->v[ti->n].status = status;
    ti->v[ti->n].path = path;
    ti->n++;
}

static int toolinfo_has(const ToolInfos *ti, const char *name)
{
    for (size_t i = 0; i < ti->n; i++)
        if (strcmp(ti->v[i].name, name) == 0)
            return 1;
    return 0;
}

static void check_tools(const Segments *segs, int path_check, ToolInfos *out)
{
    if (!path_check)
        return;
    if (!path_cache_built)
        build_path_cache();
    for (size_t si = 0; si < segs->n; si++) {
        const Segment *seg = &segs->v[si];
        if (!seg->has_head)
            continue;
        char *head = xstrndup(seg->head.p, seg->head.n);
        if (is_builtin(head) || toolinfo_has(out, head)) {
            free(head);
            continue;
        }
        if (name_in_cache(head)) {
            toolinfos_push(out, head, "found", xstrdup(head));
        } else {
            toolinfos_push(out, head, "missing", NULL);
        }
    }
}

/* ================= preflight orchestration ================= */

typedef struct {
    const char *command;
    const char *target;
    Issue *issues;
    size_t nissues;
    ToolInfo *tools;
    size_t ntools;
    double elapsed_ms;
    const char *verdict; /* "ok" | "warn" | "fail" */
    int errors;
    int warnings;
} Report;

static int severity_rank(const char *sev)
{
    if (strcmp(sev, "error") == 0)
        return 2;
    if (strcmp(sev, "warning") == 0)
        return 1;
    return 0;
}

static int report_exit_code(const Report *r)
{
    if (strcmp(r->verdict, "warn") == 0)
        return 1;
    if (strcmp(r->verdict, "fail") == 0)
        return 2;
    return 0;
}

/* names whose Windows PATH namesakes do something different, so a PATH hit
   is not evidence the command will do what the agent meant */
static int no_downgrade(const char *name) { return strcmp(name, "find") == 0; }

static int has_posix_cmd_issue(const Issue *issues, size_t n, const char *name)
{
    for (size_t i = 0; i < n; i++)
        if (strcmp(issues[i].code, "POSIX-CMD") == 0 && issues[i].tool &&
            strcmp(issues[i].tool, name) == 0)
            return 1;
    return 0;
}

/* returns 0 on success, 1 on unknown shell (*errmsg set) */
static int preflight(const char *cmd, const char *shell, int path_check,
                     Report *rep, const char **errmsg)
{
    clock_t start = clock();
    const char *target;
    if (resolve_target(shell, &target, errmsg) != 0)
        return 1;

    Tokens toks;
    memset(&toks, 0, sizeof toks);
    lex(cmd, strlen(cmd), &toks);

    Segments segs;
    memset(&segs, 0, sizeof segs);
    split_segments(&toks, &segs);

    Issues issues;
    memset(&issues, 0, sizeof issues);
    check_dialect(&toks, &segs, target, &issues);
    check_danger(&segs, &issues);

    ToolInfos tools;
    memset(&tools, 0, sizeof tools);
    check_tools(&segs, path_check, &tools);

    /* A tool reported by rules as POSIX-only but actually present on PATH
       (Git Bash in PATH etc.) downgrades from hard failure to a note. */
    for (size_t t = 0; t < tools.n; t++) {
        if (strcmp(tools.v[t].status, "found") != 0)
            continue;
        for (size_t i = 0; i < issues.n; i++) {
            Issue *iss = &issues.v[i];
            if (strcmp(iss->code, "POSIX-CMD") == 0 && iss->tool &&
                strcmp(iss->tool, tools.v[t].name) == 0 &&
                !no_downgrade(iss->tool)) {
                iss->severity = "info";
                char *m = xasprintf("%s (present on PATH, non-native)", iss->message);
                iss->message = m;
            }
        }
    }

    /* Anything reported missing on PATH gets an explicit issue: 'command
       not found' is the single largest failure mode for agents. */
    if (path_check) {
        for (size_t t = 0; t < tools.n; t++) {
            if (strcmp(tools.v[t].status, "missing") != 0)
                continue;
            if (is_builtin(tools.v[t].name))
                continue;
            if (has_posix_cmd_issue(issues.v, issues.n, tools.v[t].name))
                continue;
            char *msg = xasprintf(
                "'%s' was not found on PATH — this is a 'command not found' failure",
                tools.v[t].name);
            issues_push(&issues, "TOOL-NOT-FOUND", "error", "tool", msg,
                        "install it, or use the native equivalent",
                        tools.v[t].name);
        }
    }

    int worst = 0, errors = 0, warnings = 0;
    for (size_t i = 0; i < issues.n; i++) {
        int rank = severity_rank(issues.v[i].severity);
        if (rank > worst)
            worst = rank;
        if (strcmp(issues.v[i].severity, "error") == 0)
            errors++;
        else if (strcmp(issues.v[i].severity, "warning") == 0)
            warnings++;
    }
    static const char *const verdicts[] = { "ok", "warn", "fail" };

    rep->command = cmd;
    rep->target = target;
    rep->issues = issues.v;
    rep->nissues = issues.n;
    rep->tools = tools.v;
    rep->ntools = tools.n;
    rep->elapsed_ms = (double)(clock() - start) * 1000.0 / CLOCKS_PER_SEC;
    rep->verdict = verdicts[worst];
    rep->errors = errors;
    rep->warnings = warnings;
    return 0;
}

/* ================= report rendering ================= */

static void json_escape(Buf *b, const char *s, size_t n)
{
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        switch (c) {
        case '"':  buf_addcstr(b, "\\\""); break;
        case '\\': buf_addcstr(b, "\\\\"); break;
        case '\n': buf_addcstr(b, "\\n"); break;
        case '\t': buf_addcstr(b, "\\t"); break;
        case '\r': buf_addcstr(b, "\\r"); break;
        case '\b': buf_addcstr(b, "\\b"); break;
        case '\f': buf_addcstr(b, "\\f"); break;
        default:
            if (c < 0x20) {
                char tmp[8];
                snprintf(tmp, sizeof tmp, "\\u%04x", (unsigned)c);
                buf_addcstr(b, tmp);
            } else {
                buf_addch(b, (char)c);
            }
        }
    }
}

static void json_kv_str(Buf *b, const char *indent, const char *key,
                        const char *val, const char *comma)
{
    buf_addcstr(b, indent);
    buf_addch(b, '"');
    buf_addcstr(b, key);
    buf_addcstr(b, "\": \"");
    json_escape(b, val, strlen(val));
    buf_addcstr(b, "\"");
    if (comma)
        buf_addcstr(b, comma);
    buf_addch(b, '\n');
}

static void fmt_ms(char *out, size_t cap, double ms)
{
    double r = (double)(long)(ms * 1000.0 + 0.5) / 1000.0;
    snprintf(out, cap, "%.3f", r);
    char *dot = strchr(out, '.');
    if (dot) {
        char *end = out + strlen(out) - 1;
        while (end > dot && *end == '0')
            *end-- = '\0';
        if (end == dot)
            *end = '\0';
    }
}

static void report_to_json(const Report *r, Buf *out)
{
    buf_addcstr(out, "{\n");
    json_kv_str(out, "  ", "command", r->command, ",");
    json_kv_str(out, "  ", "target", r->target, ",");
    json_kv_str(out, "  ", "verdict", r->verdict, ",");
    buf_addcstr(out, "  \"errors\": ");
    {
        char tmp[32];
        snprintf(tmp, sizeof tmp, "%d", r->errors);
        buf_addcstr(out, tmp);
        buf_addcstr(out, ",\n");
    }
    buf_addcstr(out, "  \"warnings\": ");
    {
        char tmp[32];
        snprintf(tmp, sizeof tmp, "%d", r->warnings);
        buf_addcstr(out, tmp);
        buf_addcstr(out, ",\n");
    }
    if (r->nissues == 0) {
        buf_addcstr(out, "  \"issues\": [],\n");
    } else {
        buf_addcstr(out, "  \"issues\": [\n");
        for (size_t i = 0; i < r->nissues; i++) {
            const Issue *is = &r->issues[i];
            buf_addcstr(out, "    {\n");
            json_kv_str(out, "      ", "code", is->code, ",");
            json_kv_str(out, "      ", "severity", is->severity, ",");
            json_kv_str(out, "      ", "kind", is->kind, ",");
            json_kv_str(out, "      ", "message", is->message, is->fix || is->tool ? "," : NULL);
            if (is->fix)
                json_kv_str(out, "      ", "fix", is->fix, is->tool ? "," : NULL);
            if (is->tool)
                json_kv_str(out, "      ", "tool", is->tool, NULL);
            buf_addcstr(out, "    }");
            buf_addcstr(out, i + 1 < r->nissues ? ",\n" : "\n");
        }
        buf_addcstr(out, "  ],\n");
    }
    if (r->ntools == 0) {
        buf_addcstr(out, "  \"tools\": [],\n");
    } else {
        buf_addcstr(out, "  \"tools\": [\n");
        for (size_t i = 0; i < r->ntools; i++) {
            const ToolInfo *t = &r->tools[i];
            buf_addcstr(out, "    {\n");
            json_kv_str(out, "      ", "name", t->name, ",");
            json_kv_str(out, "      ", "status", t->status, ",");
            buf_addcstr(out, "      \"path\": ");
            if (t->path) {
                buf_addch(out, '"');
                json_escape(out, t->path, strlen(t->path));
                buf_addch(out, '"');
            } else {
                buf_addcstr(out, "null");
            }
            buf_addcstr(out, "\n    }");
            buf_addcstr(out, i + 1 < r->ntools ? ",\n" : "\n");
        }
        buf_addcstr(out, "  ],\n");
    }
    {
        char tmp[64];
        fmt_ms(tmp, sizeof tmp, r->elapsed_ms);
        buf_addcstr(out, "  \"elapsed_ms\": ");
        buf_addcstr(out, tmp);
        buf_addcstr(out, "\n}");
    }
}

static void report_to_text(const Report *r, Buf *out)
{
    buf_addcstr(out, "shpreflight: ");
    buf_addcstr(out, r->verdict);
    {
        char tmp[64];
        snprintf(tmp, sizeof tmp, " (%d error(s), %d warning(s)) for ", r->errors, r->warnings);
        buf_addcstr(out, tmp);
    }
    buf_addcstr(out, r->target);
    buf_addch(out, '\n');
    for (size_t i = 0; i < r->nissues; i++) {
        const Issue *is = &r->issues[i];
        buf_addcstr(out, "  ");
        buf_addcstr(out, is->code);
        buf_addcstr(out, " [");
        buf_addcstr(out, is->severity);
        buf_addcstr(out, "] ");
        buf_addcstr(out, is->kind);
        buf_addcstr(out, ": ");
        buf_addcstr(out, is->message);
        buf_addch(out, '\n');
        if (is->fix) {
            buf_addcstr(out, "    fix: ");
            buf_addcstr(out, is->fix);
            buf_addch(out, '\n');
        }
    }
    for (size_t i = 0; i < r->ntools; i++) {
        if (strcmp(r->tools[i].status, "missing") == 0) {
            buf_addcstr(out, "  ");
            buf_addcstr(out, r->tools[i].name);
            buf_addcstr(out, ": not found on PATH\n");
        }
    }
    if (r->nissues == 0)
        buf_addcstr(out, "  no issues found\n");
}

/* ================= CLI ================= */

static const char USAGE[] =
    "usage: shpreflight <command> [options]\n"
    "\n"
    "commands:\n"
    "  check    diagnose a command before running it\n"
    "  shells   list supported shell dialects\n"
    "\n"
    "check options:\n"
    "  --command words...    the shell command to check (quote it, or use --stdin)\n"
    "  --stdin               read the command from stdin instead\n"
    "  --shell SHELL         target shell: auto (default), powershell5, pwsh7, bash, cmd, sh\n"
    "  --format FORMAT       output for humans (text, default) or agents (json)\n"
    "  --no-path-check       skip PATH resolution of command heads\n";

static char *trim_ascii_ws(const char *s)
{
    size_t len = strlen(s);
    size_t b = 0, e = len;
    while (b < e && (s[b] == ' ' || s[b] == '\t' || s[b] == '\r' || s[b] == '\n'))
        b++;
    while (e > b && (s[e - 1] == ' ' || s[e - 1] == '\t' || s[e - 1] == '\r' || s[e - 1] == '\n'))
        e--;
    return xstrndup(s + b, e - b);
}

static int streq(const char *a, const char *b) { return strcmp(a, b) == 0; }

static int starts_with(const char *s, const char *prefix)
{
    return strncmp(s, prefix, strlen(prefix)) == 0;
}

typedef struct {
    char **pos;
    size_t npos, cappos;
    const char *shell;
    const char *format;
    int use_stdin;
    int no_path_check;
    char *err;
} CheckArgs;

static void pos_push(CheckArgs *ca, const char *s)
{
    if (ca->npos == ca->cappos) {
        ca->cappos = ca->cappos ? ca->cappos * 2 : 8;
        ca->pos = realloc(ca->pos, ca->cappos * sizeof(char *));
        if (!ca->pos) {
            fputs("shpreflight: out of memory\n", stderr);
            exit(4);
        }
    }
    ca->pos[ca->npos++] = (char *)s;
}

/* only exact matches of known flags are options; anything else (including
   "-rf", "--flag-of-the-command") is part of the command */
static int parse_check_args(int argc, char **argv, CheckArgs *ca)
{
    memset(ca, 0, sizeof *ca);
    ca->shell = "auto";
    ca->format = "text";
    int i = 0;
    while (i < argc) {
        const char *a = argv[i];
        if (streq(a, "--stdin")) {
            ca->use_stdin = 1;
        } else if (streq(a, "--no-path-check")) {
            ca->no_path_check = 1;
        } else if (streq(a, "--shell") || streq(a, "--format")) {
            if (i + 1 >= argc) {
                ca->err = xasprintf("%s requires a value", a);
                return 1;
            }
            i++;
            if (streq(a, "--shell"))
                ca->shell = argv[i];
            else
                ca->format = argv[i];
        } else if (starts_with(a, "--shell=")) {
            ca->shell = a + strlen("--shell=");
        } else if (starts_with(a, "--format=")) {
            ca->format = a + strlen("--format=");
        } else if (streq(a, "--")) {
            for (int j = i + 1; j < argc; j++)
                pos_push(ca, argv[j]);
            break;
        } else {
            pos_push(ca, a);
        }
        i++;
    }
    if (!streq(ca->format, "text") && !streq(ca->format, "json")) {
        ca->err = xasprintf("invalid --format choice: '%s' (choose from 'text', 'json')",
                            ca->format);
        return 1;
    }
    return 0;
}

static char *read_all_stdin(void)
{
    Buf b;
    memset(&b, 0, sizeof b);
    char chunk[4096];
    size_t got;
    while ((got = fread(chunk, 1, sizeof chunk, stdin)) > 0)
        buf_add(&b, chunk, got);
    if (b.n == 0)
        return xstrdup("");
    return b.p ? b.p : xstrdup("");
}

static int run_shells(FILE *out)
{
    fputs("{\n", out);
    for (size_t i = 0; i < SHELL_TABLE_LEN; i++) {
        fprintf(out, "  \"%s\": \"%s\"%s\n", shell_table[i].key, shell_table[i].desc,
                i + 1 < SHELL_TABLE_LEN ? "," : "");
    }
    fputs("}", out);
    fputc('\n', out);
    return 0;
}

static int run_check(int argc, char **argv, FILE *out, FILE *errf)
{
    CheckArgs ca;
    if (parse_check_args(argc, argv, &ca) != 0) {
        fprintf(errf, "error: %s\n", ca.err);
        return 3;
    }

    char *cmd = NULL;
    if (ca.use_stdin) {
        char *raw = read_all_stdin();
        cmd = trim_ascii_ws(raw);
    } else if (ca.npos > 0) {
        Buf b;
        memset(&b, 0, sizeof b);
        for (size_t i = 0; i < ca.npos; i++) {
            if (i > 0)
                buf_addch(&b, ' ');
            buf_addcstr(&b, ca.pos[i]);
        }
        cmd = trim_ascii_ws(b.p ? b.p : "");
    } else {
        fputs("error: no command given\n", errf);
        return 3;
    }
    if (!*cmd) {
        fputs("error: empty command\n", errf);
        return 3;
    }

    Report rep;
    memset(&rep, 0, sizeof rep);
    const char *errmsg = NULL;
    if (preflight(cmd, ca.shell, !ca.no_path_check, &rep, &errmsg) != 0) {
        fprintf(errf, "error: %s\n", errmsg);
        return 3;
    }

    Buf b;
    memset(&b, 0, sizeof b);
    if (streq(ca.format, "json"))
        report_to_json(&rep, &b);
    else
        report_to_text(&rep, &b);
    fwrite(b.p, 1, b.n, out);
    fputc('\n', out);
    return report_exit_code(&rep);
}

static int run(int argc, char **argv, FILE *out, FILE *errf)
{
    if (argc == 0) {
        fputs(USAGE, errf);
        return 3;
    }
    if (streq(argv[0], "check"))
        return run_check(argc - 1, argv + 1, out, errf);
    if (streq(argv[0], "shells"))
        return run_shells(out);
    if (streq(argv[0], "-h") || streq(argv[0], "--help") || streq(argv[0], "help")) {
        fputs(USAGE, out);
        return 0;
    }
    fprintf(errf, "error: unknown command '%s'\n", argv[0]);
    fputs(USAGE, errf);
    return 3;
}

#ifndef SHPREFLIGHT_NO_MAIN
int main(int argc, char **argv)
{
    return run(argc > 0 ? argc - 1 : 0, argv + (argc > 0 ? 1 : 0), stdout, stderr);
}
#endif
