/*
 * shpreflight.cpp — single-file C++17 port of shpreflight: pre-flight
 * diagnostics for shell commands generated by AI agents (dialect
 * compatibility, missing tools, destructive operations — before the
 * command runs).
 *
 * Build (no third-party dependencies, C++17 + standard library only):
 *   POSIX (Linux/macOS):   c++ -O2 -std=c++17 -Wall -Wextra -o shpreflight shpreflight.cpp
 *   MinGW g++ on Windows:  g++ -O2 -std=c++17 -Wall -Wextra -o shpreflight.exe shpreflight.cpp
 *   MSVC:                  cl /O2 /utf-8 /EHsc shpreflight.cpp
 *
 * The danger pattern table is generated from the Python reference
 * (cpp/patterns_gen.h, regenerated by proofs/export_patterns.py), so the
 * Python, Go, C, C++ and Rust ports share one source of truth whose recall
 * over the table itself is machine-checked in Lean 4 (proofs/Shpreflight.lean).
 *
 * The lexer preserves the machine-checked conservation invariant: the
 * concatenation of all token texts equals the input command, so no
 * destructive fragment can hide in a lexing blind spot.
 *
 * Exit codes are machine-readable so agents can branch on them:
 *   0 ok, 1 warn, 2 fail, 3 usage error.
 *
 * The embedded test binary (cpp/test_shpreflight.cpp) exercises the same
 * paths by including this file with SHPREFLIGHT_NO_MAIN defined.
 */

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#if defined(_WIN32)
#  define WIN32_LEAN_AND_MEAN
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#else
#  include <dirent.h>
#endif

#include "patterns_gen.h"

/* ================= small string helpers ================= */

static bool cstr_eq(const char* a, const char* b) { return std::strcmp(a, b) == 0; }

static bool str_contains_ch(std::string_view a, char c)
{
    return a.find(c) != std::string_view::npos;
}

static bool str_endswith(std::string_view a, std::string_view suffix)
{
    return a.size() >= suffix.size() && a.substr(a.size() - suffix.size()) == suffix;
}

static bool str_isdigit(std::string_view a)
{
    if (a.empty())
        return false;
    for (char c : a)
        if (c < '0' || c > '9')
            return false;
    return true;
}

static bool str_in_cstr_list(std::string_view w, const char* const* list, size_t n)
{
    for (size_t i = 0; i < n; i++)
        if (w == list[i])
            return true;
    return false;
}

/* ================= lexer ================= */

enum TokKind {
    TOK_WORD,
    TOK_SEP,
    TOK_OP,
    TOK_SQUOTE,
    TOK_DQUOTE,
    TOK_BACKTICK
};

struct Token {
    TokKind kind;
    std::string_view text;
};

static bool is_ws_ch(char c)
{
    return c == ' ' || c == '\t' || c == '\r' || c == '\n';
}

static bool is_op_ch(char c)
{
    return c == '&' || c == '|' || c == ';' || c == '<' || c == '>';
}

static bool is_quote_ch(char c)
{
    return c == '\'' || c == '"' || c == '`';
}

/* span of a quoted region: [i, j) including both quotes when closed */
static size_t quoted_span(std::string_view cmd, size_t i)
{
    size_t hit = cmd.find(cmd[i], i + 1);
    return hit == std::string_view::npos ? cmd.size() : hit + 1;
}

/* Single-pass lexer. Every input byte lands in exactly one token. */
static std::vector<Token> lex(std::string_view cmd)
{
    std::vector<Token> out;
    const size_t n = cmd.size();
    size_t i = 0;
    while (i < n) {
        char ch = cmd[i];
        if (is_ws_ch(ch)) {
            size_t j = i + 1;
            while (j < n && is_ws_ch(cmd[j]))
                j++;
            out.push_back({TOK_SEP, cmd.substr(i, j - i)});
            i = j;
        } else if (is_quote_ch(ch)) {
            TokKind k = ch == '\'' ? TOK_SQUOTE : (ch == '"' ? TOK_DQUOTE : TOK_BACKTICK);
            size_t j = quoted_span(cmd, i);
            out.push_back({k, cmd.substr(i, j - i)});
            i = j;
        } else if (is_op_ch(ch)) {
            size_t j = i + 1;
            while (j < n && is_op_ch(cmd[j]))
                j++;
            out.push_back({TOK_OP, cmd.substr(i, j - i)});
            i = j;
        } else {
            size_t j = i + 1;
            while (j < n && !is_op_ch(cmd[j]) && !is_ws_ch(cmd[j]) && !is_quote_ch(cmd[j]))
                j++;
            out.push_back({TOK_WORD, cmd.substr(i, j - i)});
            i = j;
        }
    }
    return out;
}

static bool tok_is_closed(const Token& t)
{
    if (t.kind != TOK_SQUOTE && t.kind != TOK_DQUOTE && t.kind != TOK_BACKTICK)
        return true;
    return t.text.size() >= 2 && t.text.front() == t.text.back();
}

/* conservation invariant: concat(token texts) == cmd (used by the tests) */
[[maybe_unused]] static bool reconstruct_eq(const std::vector<Token>& t, std::string_view cmd)
{
    size_t pos = 0;
    for (const Token& tok : t) {
        if (pos + tok.text.size() > cmd.size() ||
            cmd.substr(pos, tok.text.size()) != tok.text)
            return false;
        pos += tok.text.size();
    }
    return pos == cmd.size();
}

/* ================= segments ================= */

struct Segment {
    bool has_head = false;
    std::string_view head{};                    /* valid when has_head */
    std::vector<std::string_view> words;        /* quote-stripped, head included */
    std::vector<std::string_view> redirects;    /* redirect targets */
    bool terminated = false;                    /* a control operator follows */
    std::string_view terminator{};              /* "|", "||", ";", "&&", "&" */
};

static bool seg_pipes_out(const Segment& s)
{
    return s.terminated && s.terminator == "|";
}

static bool is_control_op(std::string_view text)
{
    return text == "|" || text == "||" || text == ";" || text == "&&" || text == "&";
}

static std::string_view strip_quotes(std::string_view w)
{
    if (w.size() >= 2 && is_quote_ch(w.front()) && w.front() == w.back())
        return w.substr(1, w.size() - 2);
    return w;
}

static std::vector<Segment> split_segments(const std::vector<Token>& toks)
{
    std::vector<Segment> out;
    std::vector<std::string_view> words, redirects;
    size_t raw_len = 0;
    bool in_redirect = false;

    auto flush = [&](std::string_view term, bool has_term) {
        if (!words.empty() || !redirects.empty() || raw_len > 0) {
            Segment s;
            s.has_head = !words.empty();
            if (s.has_head)
                s.head = words[0];
            s.words = words;
            s.redirects = redirects;
            s.terminated = has_term;
            s.terminator = term;
            out.push_back(std::move(s));
        }
        words.clear();
        redirects.clear();
        raw_len = 0;
        /* redirect state is per-segment: without this reset, every word after
           "x > f && ..." would be swallowed as a redirect target and the head
           of the next segment (e.g. an "rm -rf /") would vanish from analysis */
        in_redirect = false;
    };

    for (size_t i = 0; i < toks.size(); i++) {
        const Token& t = toks[i];
        switch (t.kind) {
        case TOK_SEP:
            raw_len += t.text.size();
            break;
        case TOK_OP:
            raw_len += t.text.size();
            if (is_control_op(t.text))
                flush(t.text, true);
            else
                in_redirect = true;
            break;
        default: { /* WORD, SQUOTE, DQUOTE, BACKTICK */
            std::string_view bare = strip_quotes(t.text);
            raw_len += t.text.size();
            const Token* nxt = (i + 1 < toks.size()) ? &toks[i + 1] : nullptr;
            if (t.kind == TOK_WORD && str_isdigit(bare) && nxt &&
                nxt->kind == TOK_OP &&
                (str_contains_ch(nxt->text, '>') || str_contains_ch(nxt->text, '<'))) {
                /* fd prefix of the next redirect: "out 2> err", "log 2>&1" */
                continue;
            }
            if (in_redirect)
                redirects.push_back(bare);
            else
                words.push_back(bare);
            break;
        }
        }
    }
    flush({}, false);
    return out;
}

/* ================= shell registry ================= */

struct ShellDef {
    const char* key;
    const char* desc;
};

static const ShellDef shell_table[] = {
    { "powershell5", "Windows PowerShell 5.1 (powershell.exe)" },
    { "pwsh7", "PowerShell 7+ (pwsh.exe)" },
    { "bash", "Bash (Git Bash / WSL / Unix)" },
    { "cmd", "Windows cmd.exe" },
    { "sh", "POSIX sh" },
};
#define SHELL_TABLE_LEN (sizeof shell_table / sizeof shell_table[0])

static const char* default_shell()
{
#if defined(_WIN32)
    return "powershell5";
#else
    return "bash";
#endif
}

/* true = ok, false = unknown shell (message in errmsg) */
static bool resolve_target(const char* shell, std::string& out, std::string& errmsg)
{
    if (!shell || !*shell || cstr_eq(shell, "auto")) {
        out = default_shell();
        return true;
    }
    for (size_t i = 0; i < SHELL_TABLE_LEN; i++) {
        if (cstr_eq(shell_table[i].key, shell)) {
            out = shell_table[i].key;
            return true;
        }
    }
    errmsg = "unknown shell '" + std::string(shell) + "'; see `shpreflight shells`";
    return false;
}

static bool is_powershell(std::string_view target)
{
    return target == "powershell5" || target == "pwsh7";
}

static bool is_windows_shell(std::string_view target)
{
    return is_powershell(target) || target == "cmd";
}

/* ================= issues ================= */

struct Issue {
    const char* code;
    const char* severity; /* "error" | "warning" | "info" */
    const char* kind;     /* "syntax" | "danger" | "tool" */
    std::string message;
    std::optional<std::string> fix;
    std::optional<std::string> tool;
};

static void issues_push(std::vector<Issue>& iss, const char* code, const char* severity,
                        const char* kind, std::string message,
                        const std::optional<std::string_view>& fix = std::nullopt,
                        const std::optional<std::string_view>& tool = std::nullopt)
{
    Issue it;
    it.code = code;
    it.severity = severity;
    it.kind = kind;
    it.message = std::move(message);
    if (fix)
        it.fix = std::string(*fix);
    if (tool)
        it.tool = std::string(*tool);
    iss.push_back(std::move(it));
}

/* ================= danger detection ================= */

static const char* const shell_heads[] = {
    "sh", "bash", "zsh", "pwsh", "powershell", "dash"
};
#define SHELL_HEADS_LEN (sizeof shell_heads / sizeof shell_heads[0])

static const char* const exec_heads[] = { "iex", "Invoke-Expression", "eval" };
#define EXEC_HEADS_LEN (sizeof exec_heads / sizeof exec_heads[0])

static const char* const sensitive_bases[] = {
    ".env", ".env.local", ".env.production", "secrets",
    "id_rsa", "id_ed25519", "credentials", "credentials.json",
    ".npmrc", ".netrc", ".aws/credentials"
};
#define SENSITIVE_BASES_LEN (sizeof sensitive_bases / sizeof sensitive_bases[0])

static bool wordlist_has(const std::vector<std::string_view>& words, std::string_view s)
{
    for (std::string_view w : words)
        if (w == s)
            return true;
    return false;
}

static bool any_word_in_list(const std::vector<std::string_view>& words, size_t start,
                             const char* const* list, size_t ln)
{
    for (size_t i = start; i < words.size(); i++)
        for (size_t j = 0; j < ln; j++)
            if (words[i] == list[j])
                return true;
    return false;
}

/* structural match: head, then any-of flags, then any-of targets */
static bool match_pattern(const std::vector<std::string_view>& words, const PatternDef* p)
{
    if (words.empty())
        return false;
    if (!str_in_cstr_list(words[0], p->heads, p->heads_len))
        return false;
    if (p->flags_len > 0 && !any_word_in_list(words, 1, p->flags, p->flags_len))
        return false;
    if (p->targets_len > 0 && !any_word_in_list(words, 1, p->targets, p->targets_len))
        return false;
    return true;
}

/* basename across both separator conventions: rsplit on '/', then on '\\',
   equals the span after the later of the two separators */
static std::string_view path_basename(std::string_view path)
{
    size_t last = std::string_view::npos;
    for (size_t i = 0; i < path.size(); i++) {
        if (path[i] == '/' || path[i] == '\\')
            last = i;
    }
    if (last == std::string_view::npos)
        return path;
    return path.substr(last + 1);
}

static void check_danger(const std::vector<Segment>& segs, std::vector<Issue>& out)
{
    bool pipe_receiver = false;
    for (const Segment& seg : segs) {
        if (seg.has_head) {
            std::string_view head = seg.head;
            if (pipe_receiver &&
                (str_in_cstr_list(head, shell_heads, SHELL_HEADS_LEN) ||
                 str_in_cstr_list(head, exec_heads, EXEC_HEADS_LEN))) {
                std::string msg = "pipe feeds untrusted input into '" + std::string(head) +
                    "' — remote-code-execution pattern (curl ... | sh)";
                issues_push(out, "PIPE-EXEC", "error", "danger", std::move(msg),
                            "download first, inspect, then run");
            }
            if (pipe_receiver && head == "npm" && wordlist_has(seg.words, "publish")) {
                issues_push(out, "NPM-PUBLISH", "warning", "danger",
                            "publishing to the npm registry makes the package public",
                            "use npm publish --dry-run until content is final");
            }
        }
        bool root_hit = false;
        for (size_t pi = 0; pi < PATTERN_TABLE_LEN; pi++) {
            const PatternDef* p = &pattern_table[pi];
            if (!match_pattern(seg.words, p))
                continue;
            /* RM-ROOT already says everything about this segment's rm */
            if (cstr_eq(p->code, "RM-RECURSIVE") && root_hit)
                continue;
            if (cstr_eq(p->code, "RM-ROOT"))
                root_hit = true;
            std::string msg = std::string(seg.words[0]) + ": " + p->message;
            issues_push(out, p->code, p->severity, "danger", std::move(msg), p->fix);
        }
        for (std::string_view redir : seg.redirects) {
            if (str_in_cstr_list(path_basename(redir), sensitive_bases, SENSITIVE_BASES_LEN) ||
                str_endswith(redir, ".key") || str_endswith(redir, ".pem")) {
                std::string msg = "overwriting sensitive file '" + std::string(redir) +
                    "' via redirection";
                issues_push(out, "REDIR-SENSITIVE", "warning", "danger", std::move(msg),
                            "write to a temp file and diff first");
            }
        }
        pipe_receiver = seg_pipes_out(seg);
    }
}

/* ================= dialect rules ================= */

static bool is_letter(char c)
{
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
}

static bool is_ident_start(char c) { return c == '_' || is_letter(c); }

static bool is_ident_char(char c) { return is_ident_start(c) || (c >= '0' && c <= '9'); }

/* fullmatch \$[A-Za-z_][A-Za-z0-9_]*$ — a bare bash variable */
static bool var_re(std::string_view s)
{
    if (s.size() < 2 || s[0] != '$' || !is_ident_start(s[1]))
        return false;
    for (size_t i = 2; i < s.size(); i++)
        if (!is_ident_char(s[i]))
            return false;
    return true;
}

/* fullmatch \$\{[A-Za-z_][A-Za-z0-9_]*\}$ */
static bool brace_var_re(std::string_view s)
{
    if (s.size() < 4 || s[0] != '$' || s[1] != '{' || s[s.size() - 1] != '}')
        return false;
    if (!is_ident_start(s[2]))
        return false;
    for (size_t i = 3; i + 1 < s.size(); i++)
        if (!is_ident_char(s[i]))
            return false;
    return true;
}

/* fullmatch [A-Z][A-Za-z]+-[A-Z][A-Za-z]+$ — a PowerShell cmdlet name */
static bool cmlet_re(std::string_view s)
{
    if (s.size() < 5 || s[0] < 'A' || s[0] > 'Z')
        return false;
    size_t i = 1, letters = 0;
    while (i < s.size() && is_letter(s[i])) {
        i++;
        letters++;
    }
    if (letters == 0 || i >= s.size() || s[i] != '-')
        return false;
    i++;
    if (i >= s.size() || s[i] < 'A' || s[i] > 'Z')
        return false;
    i++;
    letters = 0;
    while (i < s.size() && is_letter(s[i])) {
        i++;
        letters++;
    }
    return i == s.size() && letters > 0;
}

/* re.match(r"^-[a-zA-Z]+|^--[a-zA-Z-]+$"): curl-style flags */
static bool curl_flags(std::string_view w)
{
    if (w.size() >= 2 && w[0] == '-' && w[1] == '-') {
        if (w.size() == 2)
            return false;
        for (size_t i = 2; i < w.size(); i++)
            if (!is_letter(w[i]) && w[i] != '-')
                return false;
        return true;
    }
    if (w.size() >= 2 && w[0] == '-')
        return is_letter(w[1]);
    return false;
}

static const char* const special_vars[] = {
    "$?", "$!", "$$", "$#", "$@", "$*",
    "$0", "$1", "$2", "$3", "$4", "$5", "$6", "$7", "$8", "$9"
};
#define SPECIAL_VARS_LEN (sizeof special_vars / sizeof special_vars[0])

static const char* const rm_short_flags[] = { "-r", "-f", "-rf", "-fr", "-Rf", "-R" };
#define RM_SHORT_FLAGS_LEN (sizeof rm_short_flags / sizeof rm_short_flags[0])

/* POSIX commands with no Windows PowerShell 5.1 equivalent alias, plus the
   native replacement agents should switch to. */
struct PosixToPs {
    const char* name;
    const char* replacement;
};

static const PosixToPs posix_to_ps[] = {
    { "grep", "Select-String (sls)" },
    { "sed", "-replace operator" },
    { "awk", "ForEach-Object + split" },
    { "find", "Get-ChildItem -Recurse" },
    { "head", "Select-Object -First N" },
    { "tail", "Get-Content -Tail N" },
    { "touch", "New-Item -ItemType File" },
    { "chmod", "icacls" },
    { "chown", "icacls" },
    { "which", "Get-Command" },
    { "xargs", "ForEach-Object" },
    { "df", "Get-PSDrive" },
    { "du", "Get-ChildItem -Recurse | Measure-Object Length -Sum" },
    { "wc", "Measure-Object -Line/-Word/-Character" },
    { "tr", "-replace / .ToLower" },
    { "cut", ".Split()" },
    { "uniq", "Select-Object -Unique" },
    { "uname", "$env:OS" },
    { "env", "Get-ChildItem env:" },
    { "basename", "Split-Path -Leaf" },
    { "dirname", "Split-Path -Parent" },
    { "ln", "New-Item -ItemType SymbolicLink" },
    { "readlink", "(Get-Item).Target" },
    { "mktemp", "New-TemporaryFile" },
    { "stat", "Get-Item" },
    { "less", "more.com / Out-Host -Paging" },
    { "open", "Start-Process (alias on macOS only)" },
    { "make", "external: install via winget" },
};
#define POSIX_TO_PS_LEN (sizeof posix_to_ps / sizeof posix_to_ps[0])

static const char* posix_replacement_for(std::string_view head)
{
    for (size_t i = 0; i < POSIX_TO_PS_LEN; i++)
        if (head == posix_to_ps[i].name)
            return posix_to_ps[i].replacement;
    return nullptr;
}

/* renders s the way Python's repr() would (ASCII input) */
static void py_repr(std::string_view s, size_t maxlen, std::string& out)
{
    std::string_view t = s.size() > maxlen ? s.substr(0, maxlen) : s;
    bool has_single = str_contains_ch(t, '\'');
    bool has_double = str_contains_ch(t, '"');
    char q = '\'';
    if (has_single && !has_double)
        q = '"';
    out.push_back(q);
    for (char c : t) {
        if (c == '\\') {
            out += "\\\\";
        } else if (c == '\n') {
            out += "\\n";
        } else if (c == '\t') {
            out += "\\t";
        } else if (c == '\r') {
            out += "\\r";
        } else if (c == q) {
            out += '\\';
            out += c;
        } else {
            out += c;
        }
    }
    out.push_back(q);
}

static void check_dialect(const std::vector<Token>& toks, const std::vector<Segment>& segs,
                          std::string_view target, std::vector<Issue>& out)
{
    bool ps = is_powershell(target);
    bool win = is_windows_shell(target);
    bool on_bash = target == "bash" || target == "sh";
    bool ps_or_cmd = ps || target == "cmd";

    for (const Token& t : toks) {
        if ((t.kind == TOK_SQUOTE || t.kind == TOK_DQUOTE || t.kind == TOK_BACKTICK) &&
            !tok_is_closed(t)) {
            std::string m = "unclosed quote starting at ";
            py_repr(t.text, 12, m);
            m += " — the shell will hang or fail";
            issues_push(out, "UNCLOSED-QUOTE", "error", "syntax", std::move(m),
                        "close the quote");
        }
    }

    for (const Token& t : toks) {
        if (t.kind == TOK_OP) {
            if (t.text == "&&" && (target == "powershell5" || target == "cmd")) {
                issues_push(out, "SEP-AND", "error", "syntax",
                            "operator '&&' is not supported in this shell",
                            "separate commands, or chain with ';' if order alone matters");
            } else if (t.text == "||" &&
                       (target == "powershell5" || target == "cmd")) {
                issues_push(out, "SEP-OR", "error", "syntax",
                            "operator '||' is not supported in this shell",
                            "separate commands and check exit codes explicitly");
            }
        } else if (t.kind == TOK_WORD) {
            std::string_view text = t.text;
            if (text == "/dev/null" && win) {
                issues_push(out, "REDIR-DEVNULL", "error", "syntax",
                            "redirection to /dev/null — path does not exist on Windows",
                            "redirect to NUL instead:  2>NUL");
            } else if (ps_or_cmd && var_re(text)) {
                std::string msg = "bash-style variable " + std::string(text) +
                    " — PowerShell reads it as an unset PS variable";
                std::string fix = "use the environment: $env:" + std::string(text.substr(1));
                issues_push(out, "ENV-VAR", "error", "syntax", std::move(msg),
                            std::string_view(fix));
            } else if (ps && brace_var_re(text)) {
                std::string fix = "use $env:" + std::string(text.substr(2, text.size() - 3));
                issues_push(out, "BRACE-VAR", "error", "syntax",
                            "bash-style ${var} expansion is not PowerShell syntax",
                            std::string_view(fix));
            } else if (ps && str_in_cstr_list(text, special_vars, SPECIAL_VARS_LEN)) {
                std::string msg = std::string(text) +
                    " means one thing in bash and another in PowerShell "
                    "(e.g. bash $? is the numeric exit code, PS $? is a bool)";
                issues_push(out, "SPECIAL-VAR", "error", "syntax", std::move(msg),
                            "use $LASTEXITCODE for native exit codes");
            } else if (text == "export" && ps_or_cmd) {
                issues_push(out, "EXPORT", "error", "syntax",
                            "'export' is not available in this shell",
                            "PowerShell: $env:NAME = \"value\"   cmd: set NAME=value");
            } else if (text == "source" && ps) {
                issues_push(out, "SOURCE", "error", "syntax",
                            "'source' is not available in PowerShell",
                            "dot-source it:  . ./script.ps1");
            }
        } else if (t.kind == TOK_BACKTICK && ps_or_cmd) {
            issues_push(out, "BACKTICK", "error", "syntax",
                        "backticks mean command substitution in bash but are the escape "
                        "character in PowerShell — the command will do something else entirely",
                        "use $(...) for subexpressions in PowerShell");
        }
    }

    for (const Segment& seg : segs) {
        if (!seg.has_head)
            continue;
        std::string_view head = seg.head;
        if (ps && head == "curl") {
            bool any = false;
            for (size_t i = 1; i < seg.words.size(); i++) {
                if (curl_flags(seg.words[i])) {
                    any = true;
                    break;
                }
            }
            if (any) {
                issues_push(out, "CURL-ALIAS", "error", "tool",
                            "'curl' is an alias for Invoke-WebRequest in Windows PowerShell 5.1 "
                            "and rejects unix curl flags",
                            "call the real binary: curl.exe -sL ...");
            }
        }
        if (ps && (head == "rm" || head == "del" || head == "erase" || head == "rd") &&
            any_word_in_list(seg.words, 1, rm_short_flags, RM_SHORT_FLAGS_LEN)) {
            std::string msg = "'" + std::string(head) +
                "' maps to Remove-Item in PowerShell, which has no -r/-f short flags";
            issues_push(out, "RM-FLAGS", "error", "syntax", std::move(msg),
                        "Remove-Item -Recurse -Force");
        }
        if (on_bash && cmlet_re(head)) {
            std::string msg = "'" + std::string(head) + "' is a PowerShell cmdlet; "
                              "it does not exist in " + std::string(target);
            issues_push(out, "CMDLET-IN-POSIX", "error", "tool", std::move(msg),
                        "use the POSIX equivalent for this shell");
        }
        if (win) {
            const char* repl = posix_replacement_for(head);
            if (repl) {
                std::string msg = "'" + std::string(head) +
                                  "' is not a Windows PowerShell command";
                issues_push(out, "POSIX-CMD", "error", "tool", std::move(msg),
                            std::string_view(repl), head);
            }
        }
    }
}

/* ================= PATH tool resolution ================= */

/* shell builtins and Windows internal commands, kept sorted for bsearch */
static const char* const builtins[] = {
    "alias", "break", "call", "case", "cd", "chdir", "cls", "color",
    "copy", "declare", "del", "dir", "do", "done", "echo", "elif",
    "else", "endlocal", "erase", "esac", "eval", "exec", "exit",
    "export", "false", "fi", "for", "function", "if", "in", "local",
    "md", "mkdir", "move", "popd", "prompt", "pushd", "rd", "read",
    "readonly", "ren", "return", "rmdir", "set", "setlocal", "shift",
    "source", "start", "then", "title", "trap", "true", "type",
    "unset", "ver", "vol", "while", "xcopy"
};
#define BUILTINS_LEN (sizeof builtins / sizeof builtins[0])

static bool is_builtin(std::string_view name)
{
    return std::binary_search(std::begin(builtins), std::end(builtins), name,
                              [](std::string_view a, std::string_view b) { return a < b; });
}

/* reset the PATH cache (used by the embedded test to swap PATH) */
static std::vector<std::string> path_cache;
static bool path_cache_built = false;

void shp_tools_reset()
{
    path_cache.clear();
    path_cache_built = false;
}

static const char* const win_exts[] = { ".exe", ".cmd", ".bat", ".com" };
#define WIN_EXTS_LEN (sizeof win_exts / sizeof win_exts[0])

#if defined(_WIN32)
static void scan_dir(const std::string& dir, std::vector<std::string>& nv)
{
    if (dir.size() + 3 >= 1024)
        return;
    std::string pattern = dir;
    if (pattern.empty() || (pattern.back() != '\\' && pattern.back() != '/'))
        pattern += '\\';
    pattern += '*';

    WIN32_FIND_DATAA fd;
    HANDLE h = FindFirstFileA(pattern.c_str(), &fd);
    if (h == INVALID_HANDLE_VALUE)
        return;
    do {
        const char* name = fd.cFileName;
        if (cstr_eq(name, ".") || cstr_eq(name, ".."))
            continue;
        size_t n = std::strlen(name);
        nv.emplace_back(name, n);
        for (size_t e = 0; e < WIN_EXTS_LEN; e++) {
            size_t el = std::strlen(win_exts[e]);
            if (n > el && cstr_eq(name + n - el, win_exts[e])) {
                nv.emplace_back(name, n - el);
                break;
            }
        }
    } while (FindNextFileA(h, &fd));
    FindClose(h);
}
#else
static void scan_dir(const std::string& dir, std::vector<std::string>& nv)
{
    DIR* d = opendir(dir.c_str());
    if (!d)
        return;
    struct dirent* ent;
    while ((ent = readdir(d)) != NULL) {
        const char* name = ent->d_name;
        if (cstr_eq(name, ".") || cstr_eq(name, ".."))
            continue;
        nv.emplace_back(name, std::strlen(name));
    }
    closedir(d);
}
#endif

static bool name_in_cache(std::string_view name)
{
    return std::binary_search(path_cache.begin(), path_cache.end(), name,
                              [](std::string_view a, std::string_view b) { return a < b; });
}

/* one ReadDir pass over PATH; lookups after that are membership tests */
static void build_path_cache()
{
    const char* path = std::getenv("PATH");
    if (!path)
        path = "";

#if defined(_WIN32)
    const char* sep = ";";
#else
    const char* sep = ":";
#endif

    const char* p = path;
    for (;;) {
        const char* hit = std::strstr(p, sep);
        size_t len = hit ? (size_t)(hit - p) : std::strlen(p);
        if (len > 0) {
            std::string dir(p, len);
            scan_dir(dir, path_cache);
        }
        if (!hit)
            break;
        p = hit + std::strlen(sep);
    }
    std::sort(path_cache.begin(), path_cache.end());
    path_cache_built = true;
}

struct ToolInfo {
    std::string name;
    const char* status; /* "found" | "missing" */
    std::optional<std::string> path; /* name when found */
};

static bool toolinfo_has(const std::vector<ToolInfo>& ti, std::string_view name)
{
    for (const ToolInfo& t : ti)
        if (t.name == name)
            return true;
    return false;
}

static void check_tools(const std::vector<Segment>& segs, bool path_check,
                        std::vector<ToolInfo>& out)
{
    if (!path_check)
        return;
    if (!path_cache_built)
        build_path_cache();
    for (const Segment& seg : segs) {
        if (!seg.has_head)
            continue;
        std::string head(seg.head);
        if (is_builtin(head) || toolinfo_has(out, head))
            continue;
        if (name_in_cache(head))
            out.push_back({head, "found", std::optional<std::string>(head)});
        else
            out.push_back({std::move(head), "missing", std::nullopt});
    }
}

/* ================= preflight orchestration ================= */

struct Report {
    std::string command;
    std::string target;
    std::vector<Issue> issues;
    std::vector<ToolInfo> tools;
    double elapsed_ms = 0.0;
    const char* verdict = "ok"; /* "ok" | "warn" | "fail" */
    int errors = 0;
    int warnings = 0;
};

static int severity_rank(const char* sev)
{
    if (cstr_eq(sev, "error"))
        return 2;
    if (cstr_eq(sev, "warning"))
        return 1;
    return 0;
}

static int report_exit_code(const Report& r)
{
    if (cstr_eq(r.verdict, "warn"))
        return 1;
    if (cstr_eq(r.verdict, "fail"))
        return 2;
    return 0;
}

/* names whose Windows PATH namesakes do something different, so a PATH hit
   is not evidence the command will do what the agent meant */
static bool no_downgrade(std::string_view name) { return name == "find"; }

static bool has_posix_cmd_issue(const std::vector<Issue>& issues, std::string_view name)
{
    for (const Issue& iss : issues)
        if (cstr_eq(iss.code, "POSIX-CMD") && iss.tool && *iss.tool == name)
            return true;
    return false;
}

/* returns true on success, false on unknown shell (errmsg set) */
static bool preflight(const std::string& cmd, const char* shell, bool path_check,
                      Report& rep, std::string& errmsg)
{
    std::clock_t start = std::clock();
    std::string target;
    if (!resolve_target(shell, target, errmsg))
        return false;

    std::vector<Token> toks = lex(cmd);
    std::vector<Segment> segs = split_segments(toks);

    std::vector<Issue> issues;
    check_dialect(toks, segs, target, issues);
    check_danger(segs, issues);

    std::vector<ToolInfo> tools;
    check_tools(segs, path_check, tools);

    /* A tool reported by rules as POSIX-only but actually present on PATH
       (Git Bash in PATH etc.) downgrades from hard failure to a note. */
    for (const ToolInfo& t : tools) {
        if (!cstr_eq(t.status, "found"))
            continue;
        for (Issue& iss : issues) {
            if (cstr_eq(iss.code, "POSIX-CMD") && iss.tool &&
                *iss.tool == t.name && !no_downgrade(*iss.tool)) {
                iss.severity = "info";
                iss.message += " (present on PATH, non-native)";
            }
        }
    }

    /* Anything reported missing on PATH gets an explicit issue: 'command
       not found' is the single largest failure mode for agents. */
    if (path_check) {
        for (const ToolInfo& t : tools) {
            if (!cstr_eq(t.status, "missing"))
                continue;
            if (is_builtin(t.name))
                continue;
            if (has_posix_cmd_issue(issues, t.name))
                continue;
            std::string msg = "'" + t.name +
                "' was not found on PATH — this is a 'command not found' failure";
            issues_push(issues, "TOOL-NOT-FOUND", "error", "tool", std::move(msg),
                        "install it, or use the native equivalent", t.name);
        }
    }

    int worst = 0, errors = 0, warnings = 0;
    for (const Issue& iss : issues) {
        int rank = severity_rank(iss.severity);
        if (rank > worst)
            worst = rank;
        if (cstr_eq(iss.severity, "error"))
            errors++;
        else if (cstr_eq(iss.severity, "warning"))
            warnings++;
    }
    static const char* const verdicts[] = { "ok", "warn", "fail" };

    rep.command = cmd;
    rep.target = target;
    rep.issues = std::move(issues);
    rep.tools = std::move(tools);
    rep.elapsed_ms = (double)(std::clock() - start) * 1000.0 / CLOCKS_PER_SEC;
    rep.verdict = verdicts[worst];
    rep.errors = errors;
    rep.warnings = warnings;
    return true;
}

/* ================= report rendering ================= */

static void json_escape(std::string& b, std::string_view s)
{
    for (char ch : s) {
        unsigned char c = (unsigned char)ch;
        switch (c) {
        case '"':  b += "\\\""; break;
        case '\\': b += "\\\\"; break;
        case '\n': b += "\\n"; break;
        case '\t': b += "\\t"; break;
        case '\r': b += "\\r"; break;
        case '\b': b += "\\b"; break;
        case '\f': b += "\\f"; break;
        default:
            if (c < 0x20) {
                char tmp[8];
                std::snprintf(tmp, sizeof tmp, "\\u%04x", (unsigned)c);
                b += tmp;
            } else {
                b += (char)c;
            }
        }
    }
}

static void json_kv_str(std::string& b, const char* indent, const char* key,
                        std::string_view val, const char* comma)
{
    b += indent;
    b += '"';
    b += key;
    b += "\": \"";
    json_escape(b, val);
    b += '"';
    if (comma)
        b += comma;
    b += '\n';
}

static void fmt_ms(char* out, size_t cap, double ms)
{
    double r = (double)(long)(ms * 1000.0 + 0.5) / 1000.0;
    std::snprintf(out, cap, "%.3f", r);
    char* dot = std::strchr(out, '.');
    if (dot) {
        char* end = out + std::strlen(out) - 1;
        while (end > dot && *end == '0')
            *end-- = '\0';
        if (end == dot)
            *end = '\0';
    }
}

static void report_to_json(const Report& r, std::string& out)
{
    out += "{\n";
    json_kv_str(out, "  ", "command", r.command, ",");
    json_kv_str(out, "  ", "target", r.target, ",");
    json_kv_str(out, "  ", "verdict", r.verdict, ",");
    out += "  \"errors\": ";
    {
        char tmp[32];
        std::snprintf(tmp, sizeof tmp, "%d", r.errors);
        out += tmp;
        out += ",\n";
    }
    out += "  \"warnings\": ";
    {
        char tmp[32];
        std::snprintf(tmp, sizeof tmp, "%d", r.warnings);
        out += tmp;
        out += ",\n";
    }
    if (r.issues.empty()) {
        out += "  \"issues\": [],\n";
    } else {
        out += "  \"issues\": [\n";
        for (size_t i = 0; i < r.issues.size(); i++) {
            const Issue& is = r.issues[i];
            out += "    {\n";
            json_kv_str(out, "      ", "code", is.code, ",");
            json_kv_str(out, "      ", "severity", is.severity, ",");
            json_kv_str(out, "      ", "kind", is.kind, ",");
            json_kv_str(out, "      ", "message", is.message,
                        (is.fix || is.tool) ? "," : NULL);
            if (is.fix)
                json_kv_str(out, "      ", "fix", *is.fix, is.tool ? "," : NULL);
            if (is.tool)
                json_kv_str(out, "      ", "tool", *is.tool, NULL);
            out += "    }";
            out += (i + 1 < r.issues.size()) ? ",\n" : "\n";
        }
        out += "  ],\n";
    }
    if (r.tools.empty()) {
        out += "  \"tools\": [],\n";
    } else {
        out += "  \"tools\": [\n";
        for (size_t i = 0; i < r.tools.size(); i++) {
            const ToolInfo& t = r.tools[i];
            out += "    {\n";
            json_kv_str(out, "      ", "name", t.name, ",");
            json_kv_str(out, "      ", "status", t.status, ",");
            out += "      \"path\": ";
            if (t.path) {
                out += '"';
                json_escape(out, *t.path);
                out += '"';
            } else {
                out += "null";
            }
            out += "\n    }";
            out += (i + 1 < r.tools.size()) ? ",\n" : "\n";
        }
        out += "  ],\n";
    }
    {
        char tmp[64];
        fmt_ms(tmp, sizeof tmp, r.elapsed_ms);
        out += "  \"elapsed_ms\": ";
        out += tmp;
        out += "\n}";
    }
}

static void report_to_text(const Report& r, std::string& out)
{
    out += "shpreflight: ";
    out += r.verdict;
    {
        char tmp[64];
        std::snprintf(tmp, sizeof tmp, " (%d error(s), %d warning(s)) for ",
                      r.errors, r.warnings);
        out += tmp;
    }
    out += r.target;
    out += '\n';
    for (const Issue& is : r.issues) {
        out += "  ";
        out += is.code;
        out += " [";
        out += is.severity;
        out += "] ";
        out += is.kind;
        out += ": ";
        out += is.message;
        out += '\n';
        if (is.fix) {
            out += "    fix: ";
            out += *is.fix;
            out += '\n';
        }
    }
    for (const ToolInfo& t : r.tools) {
        if (cstr_eq(t.status, "missing")) {
            out += "  ";
            out += t.name;
            out += ": not found on PATH\n";
        }
    }
    if (r.issues.empty())
        out += "  no issues found\n";
}

/* ================= CLI ================= */

static const char USAGE[] =
    "usage: shpreflight <command> [options]\n"
    "\n"
    "commands:\n"
    "  check    diagnose a command before running it\n"
    "  shells   list supported shell dialects\n"
    "\n"
    "check options:\n"
    "  --command words...    the shell command to check (quote it, or use --stdin)\n"
    "  --stdin               read the command from stdin instead\n"
    "  --shell SHELL         target shell: auto (default), powershell5, pwsh7, bash, cmd, sh\n"
    "  --format FORMAT       output for humans (text, default) or agents (json)\n"
    "  --no-path-check       skip PATH resolution of command heads\n";

static std::string trim_ascii_ws(const std::string& s)
{
    size_t b = 0, e = s.size();
    auto ws = [](char c) { return c == ' ' || c == '\t' || c == '\r' || c == '\n'; };
    while (b < e && ws(s[b]))
        b++;
    while (e > b && ws(s[e - 1]))
        e--;
    return s.substr(b, e - b);
}

static bool starts_with(std::string_view s, std::string_view prefix)
{
    return s.size() >= prefix.size() && s.substr(0, prefix.size()) == prefix;
}

struct CheckArgs {
    std::vector<std::string> pos;
    std::string shell = "auto";
    std::string format = "text";
    bool use_stdin = false;
    bool no_path_check = false;
    std::string err;
};

/* only exact matches of known flags are options; anything else (including
   "-rf", "--flag-of-the-command") is part of the command */
static bool parse_check_args(int argc, const char* const* argv, CheckArgs& ca)
{
    int i = 0;
    while (i < argc) {
        const char* a = argv[i];
        if (cstr_eq(a, "--stdin")) {
            ca.use_stdin = true;
        } else if (cstr_eq(a, "--no-path-check")) {
            ca.no_path_check = true;
        } else if (cstr_eq(a, "--shell") || cstr_eq(a, "--format")) {
            if (i + 1 >= argc) {
                ca.err = std::string(a) + " requires a value";
                return false;
            }
            i++;
            if (cstr_eq(a, "--shell"))
                ca.shell = argv[i];
            else
                ca.format = argv[i];
        } else if (starts_with(a, "--shell=")) {
            ca.shell = a + 8;
        } else if (starts_with(a, "--format=")) {
            ca.format = a + 9;
        } else if (cstr_eq(a, "--")) {
            for (int j = i + 1; j < argc; j++)
                ca.pos.emplace_back(argv[j]);
            break;
        } else {
            ca.pos.emplace_back(a);
        }
        i++;
    }
    if (ca.format != "text" && ca.format != "json") {
        ca.err = "invalid --format choice: '" + ca.format +
                 "' (choose from 'text', 'json')";
        return false;
    }
    return true;
}

static std::string read_all_stdin()
{
    std::string b;
    char chunk[4096];
    size_t got;
    while ((got = std::fread(chunk, 1, sizeof chunk, stdin)) > 0)
        b.append(chunk, got);
    return b;
}

static int run_shells(std::FILE* out)
{
    std::fputs("{\n", out);
    for (size_t i = 0; i < SHELL_TABLE_LEN; i++) {
        std::fprintf(out, "  \"%s\": \"%s\"%s\n", shell_table[i].key, shell_table[i].desc,
                     i + 1 < SHELL_TABLE_LEN ? "," : "");
    }
    std::fputs("}", out);
    std::fputc('\n', out);
    return 0;
}

static int run_check(int argc, const char* const* argv, std::FILE* out, std::FILE* errf)
{
    CheckArgs ca;
    if (!parse_check_args(argc, argv, ca)) {
        std::fprintf(errf, "error: %s\n", ca.err.c_str());
        return 3;
    }

    std::string cmd;
    if (ca.use_stdin) {
        cmd = trim_ascii_ws(read_all_stdin());
    } else if (!ca.pos.empty()) {
        std::string joined;
        for (size_t i = 0; i < ca.pos.size(); i++) {
            if (i > 0)
                joined += ' ';
            joined += ca.pos[i];
        }
        cmd = trim_ascii_ws(joined);
    } else {
        std::fputs("error: no command given\n", errf);
        return 3;
    }
    if (cmd.empty()) {
        std::fputs("error: empty command\n", errf);
        return 3;
    }

    Report rep;
    std::string errmsg;
    if (!preflight(cmd, ca.shell.c_str(), !ca.no_path_check, rep, errmsg)) {
        std::fprintf(errf, "error: %s\n", errmsg.c_str());
        return 3;
    }

    std::string b;
    if (ca.format == "json")
        report_to_json(rep, b);
    else
        report_to_text(rep, b);
    std::fwrite(b.data(), 1, b.size(), out);
    std::fputc('\n', out);
    return report_exit_code(rep);
}

static int run(int argc, const char* const* argv, std::FILE* out, std::FILE* errf)
{
    if (argc == 0) {
        std::fputs(USAGE, errf);
        return 3;
    }
    if (cstr_eq(argv[0], "check"))
        return run_check(argc - 1, argv + 1, out, errf);
    if (cstr_eq(argv[0], "shells"))
        return run_shells(out);
    if (cstr_eq(argv[0], "-h") || cstr_eq(argv[0], "--help") || cstr_eq(argv[0], "help")) {
        std::fputs(USAGE, out);
        return 0;
    }
    std::fprintf(errf, "error: unknown command '%s'\n", argv[0]);
    std::fputs(USAGE, errf);
    return 3;
}

#ifndef SHPREFLIGHT_NO_MAIN
int main(int argc, char** argv)
{
    return run(argc > 0 ? argc - 1 : 0, argv + (argc > 0 ? 1 : 0), stdout, stderr);
}
#endif
