"""Export the Python danger pattern table to a Lean 4 source file.

The Lean proofs (Shpreflight.lean) are checked against the generated
Patterns.lean, so the machine-checked properties can never drift from the
actual runtime table: every regeneration re-links proof to implementation.

Run:  python proofs/export_patterns.py   (writes proofs/Patterns.lean)
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from shpreflight.danger import PATTERNS

HEADER = """/- Generated by proofs/export_patterns.py — DO NOT EDIT.
   Regenerate with: python proofs/export_patterns.py -/

"""


def lean_string(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def lean_list(items) -> str:
    items = sorted(items)
    if not items:
        return "[]"
    return "[" + ", ".join(lean_string(x) for x in items) + "]"


def pattern_def(p) -> str:
    return (f"    ⟨{lean_string(p.code)}, "
            f"{lean_list(p.heads)}, "
            f"{lean_list(p.flags)}, "
            f"{lean_list(p.targets)}⟩")


def render() -> str:
    body = ",\n".join(pattern_def(p) for p in PATTERNS)
    codes = ", ".join(lean_string(p.code) for p in PATTERNS)
    return (
        HEADER
        + "structure Pattern where\n"
        + "  code : String\n"
        + "  heads : List String\n"
        + "  flags : List String\n"
        + "  targets : List String\n"
        + "  deriving Repr\n\n"
        + "/-- The runtime danger table, exported verbatim from\n"
        + "    shpreflight.danger.PATTERNS. -/\n"
        + "def patterns : List Pattern :=\n"
        + "  [\n" + body + "\n  ]\n\n"
        + "/-- Every pattern code, in table order. -/\n"
        + f"def patternCodes : List String := [{codes}]\n")


def main() -> int:
    out = Path(__file__).resolve().parent / "Patterns.lean"
    out.write_text(render(), encoding="utf-8")
    print(f"wrote {out} ({len(PATTERNS)} patterns)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
