"""Export the Python danger pattern table to Lean 4, Go, C and Rust source files.

The Lean proofs (Shpreflight.lean) are checked against the generated
Patterns.lean, and the Go, C and Rust implementations consume the same
exported table, so all five implementations share one machine-checked
source of truth: every regeneration re-links proof and every port to the
runtime table.

Run:  python proofs/export_patterns.py
Writes:
    proofs/Patterns.lean
    internal/danger/patterns_gen.go
    c/patterns_gen.h
    rs/src/patterns_gen.rs
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from shpreflight.danger import PATTERNS

ROOT = Path(__file__).resolve().parents[1]

HEADER = """/- Generated by proofs/export_patterns.py — DO NOT EDIT.
   Regenerate with: python proofs/export_patterns.py -/

"""


def lean_string(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def lean_list(items) -> str:
    items = sorted(items)
    if not items:
        return "[]"
    return "[" + ", ".join(lean_string(x) for x in items) + "]"


def pattern_def(p) -> str:
    return (f"    ⟨{lean_string(p.code)}, "
            f"{lean_list(p.heads)}, "
            f"{lean_list(p.flags)}, "
            f"{lean_list(p.targets)}⟩")


def render_lean() -> str:
    body = ",\n".join(pattern_def(p) for p in PATTERNS)
    codes = ", ".join(lean_string(p.code) for p in PATTERNS)
    return (
        HEADER
        + "structure Pattern where\n"
        + "  code : String\n"
        + "  heads : List String\n"
        + "  flags : List String\n"
        + "  targets : List String\n"
        + "  deriving Repr\n\n"
        + "/-- The runtime danger table, exported verbatim from\n"
        + "    shpreflight.danger.PATTERNS. -/\n"
        + "def patterns : List Pattern :=\n"
        + "  [\n" + body + "\n  ]\n\n"
        + "/-- Every pattern code, in table order. -/\n"
        + f"def patternCodes : List String := [{codes}]\n")


# --- Go ---

def go_string(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def go_list(items) -> str:
    items = sorted(items)
    if not items:
        return "nil"
    return "[]string{" + ", ".join(go_string(x) for x in items) + "}"


def render_go() -> str:
    rows = []
    for p in PATTERNS:
        rows.append("\t{"
                    f"{go_string(p.code)}, {go_string(p.severity)}, "
                    f"{go_list(p.heads)}, {go_list(p.flags)}, {go_list(p.targets)}, "
                    f"{go_string(p.message)}, {go_string(p.fix)}"
                    "},")
    return (
        "package danger\n\n"
        "// Code generated by proofs/export_patterns.py from\n"
        "// shpreflight.danger.PATTERNS — DO NOT EDIT. Regenerate with:\n"
        "//   python proofs/export_patterns.py\n\n"
        "type patternDef struct {\n"
        "\tcode     string\n"
        "\tseverity string\n"
        "\theads    []string\n"
        "\tflags    []string\n"
        "\ttargets  []string\n"
        "\tmessage  string\n"
        "\tfix      string\n"
        "}\n\n"
        "// patternTable mirrors the Python danger table entry for entry.\n"
        "var patternTable = []patternDef{\n"
        + "\n".join(rows) + "\n"
        "}\n")


# --- C ---

def c_string(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def c_list(name: str, items) -> str:
    items = sorted(items)
    if not items:
        return f"static const char *const {name}[] = {{0}};"
    vals = ", ".join(c_string(x) for x in items)
    return f"static const char *const {name}[] = {{{vals}}};"


def render_c() -> str:
    decls = []
    rows = []
    for i, p in enumerate(PATTERNS):
        h, f, t = f"p{i}_heads", f"p{i}_flags", f"p{i}_targets"
        decls.append(c_list(h, p.heads))
        decls.append(c_list(f, p.flags))
        decls.append(c_list(t, p.targets))
        rows.append("\t{"
                    f"{c_string(p.code)}, {c_string(p.severity)}, "
                    f"{h}, {len(p.heads)}, {f}, {len(p.flags)}, "
                    f"{t}, {len(p.targets)}, "
                    f"{c_string(p.message)}, {c_string(p.fix)}"
                    "},")
    return (
        "/* Generated by proofs/export_patterns.py from\n"
        "   shpreflight.danger.PATTERNS — DO NOT EDIT. Regenerate with:\n"
        "   python proofs/export_patterns.py */\n"
        "#ifndef SHPREFLIGHT_PATTERNS_GEN_H\n"
        "#define SHPREFLIGHT_PATTERNS_GEN_H\n\n"
        "#include <stddef.h>\n\n"
        "typedef struct {\n"
        "\tconst char *code;\n"
        "\tconst char *severity;\n"
        "\tconst char *const *heads;\n"
        "\tsize_t heads_len;\n"
        "\tconst char *const *flags;\n"
        "\tsize_t flags_len;\n"
        "\tconst char *const *targets;\n"
        "\tsize_t targets_len;\n"
        "\tconst char *message;\n"
        "\tconst char *fix;\n"
        "} PatternDef;\n\n"
        + "\n".join(decls) + "\n\n"
        + "static const PatternDef pattern_table[] = {\n"
        + "\n".join(rows) + "\n"
        + "};\n\n"
        f"#define PATTERN_TABLE_LEN {len(PATTERNS)}\n\n"
        "#endif /* SHPREFLIGHT_PATTERNS_GEN_H */\n")


# --- Rust ---

def rust_string(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def rust_list(items) -> str:
    items = sorted(items)
    if not items:
        return "&[]"
    return "&[" + ", ".join(rust_string(x) for x in items) + "]"


def render_rust() -> str:
    rows = []
    for p in PATTERNS:
        fix = p.fix or ""
        rows.append(
            "    PatternDef {\n"
            f"        code: {rust_string(p.code)},\n"
            f"        severity: {rust_string(p.severity)},\n"
            f"        heads: {rust_list(p.heads)},\n"
            f"        flags: {rust_list(p.flags)},\n"
            f"        targets: {rust_list(p.targets)},\n"
            f"        message: {rust_string(p.message)},\n"
            f"        fix: {rust_string(fix)},\n"
            "    },")
    return (
        "// Generated by proofs/export_patterns.py from shpreflight.danger.PATTERNS\n"
        "// — DO NOT EDIT. Regenerate with: python proofs/export_patterns.py\n\n"
        "pub struct PatternDef {\n"
        "    pub code: &'static str,\n"
        "    pub severity: &'static str,\n"
        "    pub heads: &'static [&'static str],\n"
        "    pub flags: &'static [&'static str],\n"
        "    pub targets: &'static [&'static str],\n"
        "    pub message: &'static str,\n"
        "    pub fix: &'static str,\n"
        "}\n\n"
        "/// Mirrors the Python danger table entry for entry.\n"
        "pub static PATTERNS: &[PatternDef] = &[\n"
        + "\n".join(rows) + "\n"
        "];\n")


def main() -> int:
    outs = [
        (ROOT / "proofs" / "Patterns.lean", render_lean()),
        (ROOT / "internal" / "danger" / "patterns_gen.go", render_go()),
        (ROOT / "c" / "patterns_gen.h", render_c()),
        (ROOT / "rs" / "src" / "patterns_gen.rs", render_rust()),
    ]
    for path, text in outs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path} ({len(PATTERNS)} patterns)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
