/- Generated by proofs/export_patterns.py — DO NOT EDIT.
   Regenerate with: python proofs/export_patterns.py -/

structure Pattern where
  code : String
  heads : List String
  flags : List String
  targets : List String
  deriving Repr

/-- The runtime danger table, exported verbatim from
    shpreflight.danger.PATTERNS. -/
def patterns : List Pattern :=
  [
    ⟨"RM-ROOT", ["rm"], ["-R", "-RF", "-Rf", "-f", "-fr", "-r", "-rf"], ["$HOME", "$HOME/", "$PWD", "%SYSTEMROOT%", "*", ".", "..", "/", "/*", "C:/", "C:\\", "C:\\Windows", "~", "~/*"]⟩,
    ⟨"RM-RECURSIVE", ["rm"], ["-R", "-Rf", "-fr", "-r", "-rf"], []⟩,
    ⟨"REMOVE-ITEM-RECURSE-FORCE", ["Remove-Item", "del", "erase", "rd", "ri"], ["-Force", "-Recurse", "/f", "/q", "/s"], []⟩,
    ⟨"GIT-RESET-HARD", ["git"], ["--hard"], []⟩,
    ⟨"GIT-PUSH-FORCE", ["git"], ["--force", "--force-with-lease", "-f"], []⟩,
    ⟨"GIT-CLEAN-ND", ["git"], ["-X", "-d", "-f", "-fd", "-fdx", "-x", "clean"], []⟩,
    ⟨"SHUTDOWN", ["halt", "poweroff", "reboot", "restart", "shutdown"], [], []⟩,
    ⟨"FORMAT", ["format", "mkfs", "mkfs.ext4", "mkfs.vfat"], [], []⟩,
    ⟨"DD-RAW", ["dd"], [], ["/dev/hda", "/dev/nvme0n1", "/dev/sda", "/dev/sdb"]⟩,
    ⟨"CHMOD-777-ROOT", ["chmod"], [], ["$HOME", "*", "/", "/*", "~", "~/*"]⟩,
    ⟨"SHRED", ["shred", "srm"], [], []⟩,
    ⟨"TASKKILL-FORCE", ["taskkill"], ["-f", "/f"], []⟩,
    ⟨"SET-EXECUTIONPOLICY", ["Set-ExecutionPolicy"], ["-Force", "-Scope", "Bypass", "Process"], []⟩,
    ⟨"TRUNCATE", ["truncate"], [], []⟩
  ]

/-- Every pattern code, in table order. -/
def patternCodes : List String := ["RM-ROOT", "RM-RECURSIVE", "REMOVE-ITEM-RECURSE-FORCE", "GIT-RESET-HARD", "GIT-PUSH-FORCE", "GIT-CLEAN-ND", "SHUTDOWN", "FORMAT", "DD-RAW", "CHMOD-777-ROOT", "SHRED", "TASKKILL-FORCE", "SET-EXECUTIONPOLICY", "TRUNCATE"]
