//! shpreflight — pre-flight diagnostics for shell commands generated by AI
//! agents: dialect compatibility, missing tools, destructive operations,
//! before the command runs.
//!
//! This is the Rust port of the Python reference implementation; the danger
//! pattern table is generated from the same machine-checked source of truth
//! (proofs/export_patterns.py).

pub mod check;
pub mod cli;
pub mod danger;
pub mod lex;
pub mod report;
pub mod rules;
pub mod segments;
pub mod shells;
pub mod tools;
